<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.arctel</groupId>
        <artifactId>fyrn-mms</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>fyrn-mms-domain</artifactId>
    <name>Fyrn MMS - Domain Layer</name>
    <description>MMS Domain 层</description>


    <dependencies>
        <!-- MyBatis Plus (Service 接口继承 IService, 3.5.9 版本在 spring 包里) -->
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-spring</artifactId>
        </dependency>
    </dependencies>
</project>