<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.arctel</groupId>
        <artifactId>fyrn</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <groupId>net.arctel.platform</groupId>
    <artifactId>framework</artifactId>
    <packaging>pom</packaging>


    <name>Framework - 技术框架</name>
    <description>技术框架</description>

    <modules>
        <module>framework-core</module>
        <module>framework-web</module>
        <module>framework-common</module>
    </modules>

    <properties>
        <!-- OPKIT 版本号, 独立于主项目版本 -->
        <framework.version>${project.version}</framework.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>net.arctel.platform</groupId>
                <artifactId>framework-common</artifactId>
                <version>${framework.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>