/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ResultOmsTask,
  ResultString,
} from '../models/index';
import {
    ResultOmsTaskFromJSON,
    ResultOmsTaskToJSON,
    ResultStringFromJSON,
    ResultStringToJSON,
} from '../models/index';

export interface SyncFileToOssPostRequest {
    size?: number;
}

/**
 * 
 */
export class DataSyncControllerApi extends runtime.BaseAPI {

    /**
     * 
     * 同步本地文件到OSS
     */
    async syncFileToOssPostRaw(requestParameters: SyncFileToOssPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultString>> {
        const queryParameters: any = {};

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/sync/fileToOss`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultStringFromJSON(jsonValue));
    }

    /**
     * 
     * 同步本地文件到OSS
     */
    async syncFileToOssPost(requestParameters: SyncFileToOssPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultString> {
        const response = await this.syncFileToOssPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * 同步小说任务
     */
    async syncOssToMmsPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultOmsTask>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/sync/ossToMms`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultOmsTaskFromJSON(jsonValue));
    }

    /**
     * 
     * 同步小说任务
     */
    async syncOssToMmsPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultOmsTask> {
        const response = await this.syncOssToMmsPostRaw(initOverrides);
        return await response.value();
    }

}
