/* tslint:disable */
/* eslint-disable */
/**
 * 个人项目
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ResultBaseQueryPageOmsJob,
  ResultBoolean,
  ResultOmsJob,
  ResultString,
} from '../models/index';
import {
    ResultBaseQueryPageOmsJobFromJSON,
    ResultBaseQueryPageOmsJobToJSON,
    ResultBooleanFromJSON,
    ResultBooleanToJSON,
    ResultOmsJobFromJSON,
    ResultOmsJobToJSON,
    ResultStringFromJSON,
    ResultStringToJSON,
} from '../models/index';

export interface OmsJobCreatePostRequest {
    operator: string;
    taskType?: string;
    message?: string;
}

export interface OmsJobDetailGetRequest {
    operator: string;
    jobId?: string;
}

export interface OmsJobListGetRequest {
    operator: string;
    pageNo?: number;
    pageSize?: number;
    jobId?: string;
    taskType?: string;
    status?: number;
}

export interface OmsJobLogPostRequest {
    logId?: string;
}

export interface OmsJobUpdateJobPostRequest {
    operator: string;
    jobId?: string;
    status?: number;
    message?: string;
}

export interface OmsJobUpdateProgressPostRequest {
    operator: string;
    jobId?: string;
    log?: string;
    jobProgressDtoCurrent?: number;
    jobProgressDtoTotal?: number;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * 
     * 创建新任务
     */
    async omsJobCreatePostRaw(requestParameters: OmsJobCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultOmsJob>> {
        if (requestParameters['operator'] == null) {
            throw new runtime.RequiredError(
                'operator',
                'Required parameter "operator" was null or undefined when calling omsJobCreatePost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['operator'] != null) {
            queryParameters['operator'] = requestParameters['operator'];
        }

        if (requestParameters['taskType'] != null) {
            queryParameters['task_type'] = requestParameters['taskType'];
        }

        if (requestParameters['message'] != null) {
            queryParameters['message'] = requestParameters['message'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/oms/job/create`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultOmsJobFromJSON(jsonValue));
    }

    /**
     * 
     * 创建新任务
     */
    async omsJobCreatePost(requestParameters: OmsJobCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultOmsJob> {
        const response = await this.omsJobCreatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * 获取任务详情
     */
    async omsJobDetailGetRaw(requestParameters: OmsJobDetailGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultOmsJob>> {
        if (requestParameters['operator'] == null) {
            throw new runtime.RequiredError(
                'operator',
                'Required parameter "operator" was null or undefined when calling omsJobDetailGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['operator'] != null) {
            queryParameters['operator'] = requestParameters['operator'];
        }

        if (requestParameters['jobId'] != null) {
            queryParameters['jobId'] = requestParameters['jobId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/oms/job/detail`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultOmsJobFromJSON(jsonValue));
    }

    /**
     * 
     * 获取任务详情
     */
    async omsJobDetailGet(requestParameters: OmsJobDetailGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultOmsJob> {
        const response = await this.omsJobDetailGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * 获取任务列表
     */
    async omsJobListGetRaw(requestParameters: OmsJobListGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultBaseQueryPageOmsJob>> {
        if (requestParameters['operator'] == null) {
            throw new runtime.RequiredError(
                'operator',
                'Required parameter "operator" was null or undefined when calling omsJobListGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['operator'] != null) {
            queryParameters['operator'] = requestParameters['operator'];
        }

        if (requestParameters['pageNo'] != null) {
            queryParameters['pageNo'] = requestParameters['pageNo'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['jobId'] != null) {
            queryParameters['jobId'] = requestParameters['jobId'];
        }

        if (requestParameters['taskType'] != null) {
            queryParameters['taskType'] = requestParameters['taskType'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/oms/job/list`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultBaseQueryPageOmsJobFromJSON(jsonValue));
    }

    /**
     * 
     * 获取任务列表
     */
    async omsJobListGet(requestParameters: OmsJobListGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultBaseQueryPageOmsJob> {
        const response = await this.omsJobListGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * 获取任务日志
     */
    async omsJobLogPostRaw(requestParameters: OmsJobLogPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultString>> {
        const queryParameters: any = {};

        if (requestParameters['logId'] != null) {
            queryParameters['logId'] = requestParameters['logId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/oms/job/log`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultStringFromJSON(jsonValue));
    }

    /**
     * 
     * 获取任务日志
     */
    async omsJobLogPost(requestParameters: OmsJobLogPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultString> {
        const response = await this.omsJobLogPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * 更新任务信息
     */
    async omsJobUpdateJobPostRaw(requestParameters: OmsJobUpdateJobPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultBoolean>> {
        if (requestParameters['operator'] == null) {
            throw new runtime.RequiredError(
                'operator',
                'Required parameter "operator" was null or undefined when calling omsJobUpdateJobPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['operator'] != null) {
            queryParameters['operator'] = requestParameters['operator'];
        }

        if (requestParameters['jobId'] != null) {
            queryParameters['jobId'] = requestParameters['jobId'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['message'] != null) {
            queryParameters['message'] = requestParameters['message'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/oms/job/updateJob`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultBooleanFromJSON(jsonValue));
    }

    /**
     * 
     * 更新任务信息
     */
    async omsJobUpdateJobPost(requestParameters: OmsJobUpdateJobPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultBoolean> {
        const response = await this.omsJobUpdateJobPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * 更新任务进度
     */
    async omsJobUpdateProgressPostRaw(requestParameters: OmsJobUpdateProgressPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultBoolean>> {
        if (requestParameters['operator'] == null) {
            throw new runtime.RequiredError(
                'operator',
                'Required parameter "operator" was null or undefined when calling omsJobUpdateProgressPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['operator'] != null) {
            queryParameters['operator'] = requestParameters['operator'];
        }

        if (requestParameters['jobId'] != null) {
            queryParameters['jobId'] = requestParameters['jobId'];
        }

        if (requestParameters['log'] != null) {
            queryParameters['log'] = requestParameters['log'];
        }

        if (requestParameters['jobProgressDtoCurrent'] != null) {
            queryParameters['jobProgressDto.current'] = requestParameters['jobProgressDtoCurrent'];
        }

        if (requestParameters['jobProgressDtoTotal'] != null) {
            queryParameters['jobProgressDto.total'] = requestParameters['jobProgressDtoTotal'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/oms/job/updateProgress`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultBooleanFromJSON(jsonValue));
    }

    /**
     * 
     * 更新任务进度
     */
    async omsJobUpdateProgressPost(requestParameters: OmsJobUpdateProgressPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultBoolean> {
        const response = await this.omsJobUpdateProgressPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
