/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MmsMeta,
  ResultBaseQueryPageMmsMeta,
  ResultBoolean,
  ResultMmsMeta,
} from '../models/index';
import {
    MmsMetaFromJSON,
    MmsMetaToJSON,
    ResultBaseQueryPageMmsMetaFromJSON,
    ResultBaseQueryPageMmsMetaToJSON,
    ResultBooleanFromJSON,
    ResultBooleanToJSON,
    ResultMmsMetaFromJSON,
    ResultMmsMetaToJSON,
} from '../models/index';

export interface MmsMetaDeletePostRequest {
    id: number;
}

export interface MmsMetaIdGetRequest {
    id: number;
}

export interface MmsMetaPageGetRequest {
    pageNo?: number;
    pageSize?: number;
    novelId?: number;
    novelTitle?: string;
    novelAuthor?: string;
}

export interface MmsMetaPostRequest {
    mmsMeta?: MmsMeta;
}

export interface MmsMetaUpdatePostRequest {
    mmsMeta?: MmsMeta;
}

/**
 * 
 */
export class MmsMetaControllerApi extends runtime.BaseAPI {

    /**
     * 
     * 删除小说元数据
     */
    async mmsMetaDeletePostRaw(requestParameters: MmsMetaDeletePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultBoolean>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling mmsMetaDeletePost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/mms/meta/delete`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultBooleanFromJSON(jsonValue));
    }

    /**
     * 
     * 删除小说元数据
     */
    async mmsMetaDeletePost(requestParameters: MmsMetaDeletePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultBoolean> {
        const response = await this.mmsMetaDeletePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * 根据ID查询小说元数据
     */
    async mmsMetaIdGetRaw(requestParameters: MmsMetaIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultMmsMeta>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling mmsMetaIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/mms/meta/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultMmsMetaFromJSON(jsonValue));
    }

    /**
     * 
     * 根据ID查询小说元数据
     */
    async mmsMetaIdGet(requestParameters: MmsMetaIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultMmsMeta> {
        const response = await this.mmsMetaIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * 小说元数据分页列表
     */
    async mmsMetaPageGetRaw(requestParameters: MmsMetaPageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultBaseQueryPageMmsMeta>> {
        const queryParameters: any = {};

        if (requestParameters['pageNo'] != null) {
            queryParameters['pageNo'] = requestParameters['pageNo'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['novelId'] != null) {
            queryParameters['novelId'] = requestParameters['novelId'];
        }

        if (requestParameters['novelTitle'] != null) {
            queryParameters['novelTitle'] = requestParameters['novelTitle'];
        }

        if (requestParameters['novelAuthor'] != null) {
            queryParameters['novelAuthor'] = requestParameters['novelAuthor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/mms/meta/page`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultBaseQueryPageMmsMetaFromJSON(jsonValue));
    }

    /**
     * 
     * 小说元数据分页列表
     */
    async mmsMetaPageGet(requestParameters: MmsMetaPageGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultBaseQueryPageMmsMeta> {
        const response = await this.mmsMetaPageGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * 创建小说元数据
     */
    async mmsMetaPostRaw(requestParameters: MmsMetaPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultBoolean>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/mms/meta`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MmsMetaToJSON(requestParameters['mmsMeta']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultBooleanFromJSON(jsonValue));
    }

    /**
     * 
     * 创建小说元数据
     */
    async mmsMetaPost(requestParameters: MmsMetaPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultBoolean> {
        const response = await this.mmsMetaPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * 更新小说元数据
     */
    async mmsMetaUpdatePostRaw(requestParameters: MmsMetaUpdatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultBoolean>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/mms/meta/update`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MmsMetaToJSON(requestParameters['mmsMeta']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultBooleanFromJSON(jsonValue));
    }

    /**
     * 
     * 更新小说元数据
     */
    async mmsMetaUpdatePost(requestParameters: MmsMetaUpdatePostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultBoolean> {
        const response = await this.mmsMetaUpdatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
