/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ResultBaseQueryPageMmsNovel,
  ResultListMmsNovelFile,
} from '../models/index';
import {
    ResultBaseQueryPageMmsNovelFromJSON,
    ResultBaseQueryPageMmsNovelToJSON,
    ResultListMmsNovelFileFromJSON,
    ResultListMmsNovelFileToJSON,
} from '../models/index';

export interface MmsFileGetRequest {
    mmsNovelId: string;
}

export interface MmsPageGetRequest {
    pageNo?: number;
    pageSize?: number;
    novelId?: string;
    novelTitle?: string;
    novelAuthor?: string;
}

/**
 * 
 */
export class MmsNovelControllerApi extends runtime.BaseAPI {

    /**
     * 
     * 查询物料文件列表
     */
    async mmsFileGetRaw(requestParameters: MmsFileGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultListMmsNovelFile>> {
        if (requestParameters['mmsNovelId'] == null) {
            throw new runtime.RequiredError(
                'mmsNovelId',
                'Required parameter "mmsNovelId" was null or undefined when calling mmsFileGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['mmsNovelId'] != null) {
            queryParameters['mmsNovelId'] = requestParameters['mmsNovelId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/mms/file`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultListMmsNovelFileFromJSON(jsonValue));
    }

    /**
     * 
     * 查询物料文件列表
     */
    async mmsFileGet(requestParameters: MmsFileGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultListMmsNovelFile> {
        const response = await this.mmsFileGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * 小说分页列表
     */
    async mmsPageGetRaw(requestParameters: MmsPageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultBaseQueryPageMmsNovel>> {
        const queryParameters: any = {};

        if (requestParameters['pageNo'] != null) {
            queryParameters['pageNo'] = requestParameters['pageNo'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['novelId'] != null) {
            queryParameters['novelId'] = requestParameters['novelId'];
        }

        if (requestParameters['novelTitle'] != null) {
            queryParameters['novelTitle'] = requestParameters['novelTitle'];
        }

        if (requestParameters['novelAuthor'] != null) {
            queryParameters['novelAuthor'] = requestParameters['novelAuthor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/mms/page`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultBaseQueryPageMmsNovelFromJSON(jsonValue));
    }

    /**
     * 
     * 小说分页列表
     */
    async mmsPageGet(requestParameters: MmsPageGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultBaseQueryPageMmsNovel> {
        const response = await this.mmsPageGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
