/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ResultString,
  ResultUserInfoVo,
} from '../models/index';
import {
    ResultStringFromJSON,
    ResultStringToJSON,
    ResultUserInfoVoFromJSON,
    ResultUserInfoVoToJSON,
} from '../models/index';

export interface OmsAuthLoginPostRequest {
    username?: string;
    password?: string;
}

export interface OmsAuthRegisterPostRequest {
    username?: string;
    password?: string;
    nickname?: string;
    email?: string;
    phone?: string;
    status?: number;
}

/**
 * 
 */
export class OmsAuthControllerApi extends runtime.BaseAPI {

    /**
     * 
     * 获取当前登录用户信息
     */
    async omsAuthInfoGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultUserInfoVo>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/oms/auth/info`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultUserInfoVoFromJSON(jsonValue));
    }

    /**
     * 
     * 获取当前登录用户信息
     */
    async omsAuthInfoGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultUserInfoVo> {
        const response = await this.omsAuthInfoGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * 
     * 用户登录
     */
    async omsAuthLoginPostRaw(requestParameters: OmsAuthLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultUserInfoVo>> {
        const queryParameters: any = {};

        if (requestParameters['username'] != null) {
            queryParameters['username'] = requestParameters['username'];
        }

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/oms/auth/login`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultUserInfoVoFromJSON(jsonValue));
    }

    /**
     * 
     * 用户登录
     */
    async omsAuthLoginPost(requestParameters: OmsAuthLoginPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultUserInfoVo> {
        const response = await this.omsAuthLoginPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * 用户注册
     */
    async omsAuthRegisterPostRaw(requestParameters: OmsAuthRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultString>> {
        const queryParameters: any = {};

        if (requestParameters['username'] != null) {
            queryParameters['username'] = requestParameters['username'];
        }

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        if (requestParameters['nickname'] != null) {
            queryParameters['nickname'] = requestParameters['nickname'];
        }

        if (requestParameters['email'] != null) {
            queryParameters['email'] = requestParameters['email'];
        }

        if (requestParameters['phone'] != null) {
            queryParameters['phone'] = requestParameters['phone'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/oms/auth/register`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultStringFromJSON(jsonValue));
    }

    /**
     * 
     * 用户注册
     */
    async omsAuthRegisterPost(requestParameters: OmsAuthRegisterPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultString> {
        const response = await this.omsAuthRegisterPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
