/* tslint:disable */
/* eslint-disable */
/**
 * 个人项目
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddParameterInput,
  ResultBaseQueryPageOmsParameter,
  ResultString,
} from '../models/index';
import {
    AddParameterInputFromJSON,
    AddParameterInputToJSON,
    ResultBaseQueryPageOmsParameterFromJSON,
    ResultBaseQueryPageOmsParameterToJSON,
    ResultStringFromJSON,
    ResultStringToJSON,
} from '../models/index';

export interface OmsParameterEditPostRequest {
    addParameterInput?: AddParameterInput;
}

export interface OmsParameterPageGetRequest {
    operator: string;
    pageNo?: number;
    pageSize?: number;
    paramCode?: number;
    paramName?: string;
    enabledFlag?: number;
}

/**
 * 
 */
export class OmsParameterControllerApi extends runtime.BaseAPI {

    /**
     * 
     * 修改系统参数
     */
    async omsParameterEditPostRaw(requestParameters: OmsParameterEditPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultString>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/oms/parameter/edit`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddParameterInputToJSON(requestParameters['addParameterInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultStringFromJSON(jsonValue));
    }

    /**
     * 
     * 修改系统参数
     */
    async omsParameterEditPost(requestParameters: OmsParameterEditPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultString> {
        const response = await this.omsParameterEditPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * 分页查询参数列表
     */
    async omsParameterPageGetRaw(requestParameters: OmsParameterPageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultBaseQueryPageOmsParameter>> {
        if (requestParameters['operator'] == null) {
            throw new runtime.RequiredError(
                'operator',
                'Required parameter "operator" was null or undefined when calling omsParameterPageGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['operator'] != null) {
            queryParameters['operator'] = requestParameters['operator'];
        }

        if (requestParameters['pageNo'] != null) {
            queryParameters['pageNo'] = requestParameters['pageNo'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['paramCode'] != null) {
            queryParameters['paramCode'] = requestParameters['paramCode'];
        }

        if (requestParameters['paramName'] != null) {
            queryParameters['paramName'] = requestParameters['paramName'];
        }

        if (requestParameters['enabledFlag'] != null) {
            queryParameters['enabledFlag'] = requestParameters['enabledFlag'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/oms/parameter/page`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultBaseQueryPageOmsParameterFromJSON(jsonValue));
    }

    /**
     * 
     * 分页查询参数列表
     */
    async omsParameterPageGet(requestParameters: OmsParameterPageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultBaseQueryPageOmsParameter> {
        const response = await this.omsParameterPageGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
