/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ResultBaseQueryPageOmsTask,
  ResultBoolean,
  ResultString,
  ResultTaskDetailOutput,
  ResultTaskMonitorOutput,
} from '../models/index';
import {
    ResultBaseQueryPageOmsTaskFromJSON,
    ResultBaseQueryPageOmsTaskToJSON,
    ResultBooleanFromJSON,
    ResultBooleanToJSON,
    ResultStringFromJSON,
    ResultStringToJSON,
    ResultTaskDetailOutputFromJSON,
    ResultTaskDetailOutputToJSON,
    ResultTaskMonitorOutputFromJSON,
    ResultTaskMonitorOutputToJSON,
} from '../models/index';

export interface OmsTaskDetailGetRequest {
    taskId?: string;
}

export interface OmsTaskListGetRequest {
    pageNo?: number;
    pageSize?: number;
    taskId?: string;
    taskTag?: string;
    status?: number;
}

export interface OmsTaskLogPostRequest {
    logId?: string;
}

export interface OmsTaskUpdateProgressPostRequest {
    taskId?: string;
    log?: string;
    taskProgressDTOCurrent?: number;
    taskProgressDTOTotal?: number;
}

export interface OmsTaskUpdateTaskPostRequest {
    taskId?: string;
    status?: number;
    message?: string;
}

/**
 * 
 */
export class OmsTaskControllerApi extends runtime.BaseAPI {

    /**
     * 
     * 获取任务详情
     */
    async omsTaskDetailGetRaw(requestParameters: OmsTaskDetailGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultTaskDetailOutput>> {
        const queryParameters: any = {};

        if (requestParameters['taskId'] != null) {
            queryParameters['taskId'] = requestParameters['taskId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/oms/task/detail`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultTaskDetailOutputFromJSON(jsonValue));
    }

    /**
     * 
     * 获取任务详情
     */
    async omsTaskDetailGet(requestParameters: OmsTaskDetailGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultTaskDetailOutput> {
        const response = await this.omsTaskDetailGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * 获取任务列表
     */
    async omsTaskListGetRaw(requestParameters: OmsTaskListGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultBaseQueryPageOmsTask>> {
        const queryParameters: any = {};

        if (requestParameters['pageNo'] != null) {
            queryParameters['pageNo'] = requestParameters['pageNo'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['taskId'] != null) {
            queryParameters['taskId'] = requestParameters['taskId'];
        }

        if (requestParameters['taskTag'] != null) {
            queryParameters['taskTag'] = requestParameters['taskTag'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/oms/task/list`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultBaseQueryPageOmsTaskFromJSON(jsonValue));
    }

    /**
     * 
     * 获取任务列表
     */
    async omsTaskListGet(requestParameters: OmsTaskListGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultBaseQueryPageOmsTask> {
        const response = await this.omsTaskListGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * 获取任务日志
     */
    async omsTaskLogPostRaw(requestParameters: OmsTaskLogPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultString>> {
        const queryParameters: any = {};

        if (requestParameters['logId'] != null) {
            queryParameters['logId'] = requestParameters['logId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/oms/task/log`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultStringFromJSON(jsonValue));
    }

    /**
     * 
     * 获取任务日志
     */
    async omsTaskLogPost(requestParameters: OmsTaskLogPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultString> {
        const response = await this.omsTaskLogPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * 任务监控
     */
    async omsTaskMonitorGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultTaskMonitorOutput>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/oms/task/monitor`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultTaskMonitorOutputFromJSON(jsonValue));
    }

    /**
     * 
     * 任务监控
     */
    async omsTaskMonitorGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultTaskMonitorOutput> {
        const response = await this.omsTaskMonitorGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * 
     * 更新任务进度
     */
    async omsTaskUpdateProgressPostRaw(requestParameters: OmsTaskUpdateProgressPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultBoolean>> {
        const queryParameters: any = {};

        if (requestParameters['taskId'] != null) {
            queryParameters['taskId'] = requestParameters['taskId'];
        }

        if (requestParameters['log'] != null) {
            queryParameters['log'] = requestParameters['log'];
        }

        if (requestParameters['taskProgressDTOCurrent'] != null) {
            queryParameters['taskProgressDTO.current'] = requestParameters['taskProgressDTOCurrent'];
        }

        if (requestParameters['taskProgressDTOTotal'] != null) {
            queryParameters['taskProgressDTO.total'] = requestParameters['taskProgressDTOTotal'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/oms/task/updateProgress`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultBooleanFromJSON(jsonValue));
    }

    /**
     * 
     * 更新任务进度
     */
    async omsTaskUpdateProgressPost(requestParameters: OmsTaskUpdateProgressPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultBoolean> {
        const response = await this.omsTaskUpdateProgressPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * 更新任务信息
     */
    async omsTaskUpdateTaskPostRaw(requestParameters: OmsTaskUpdateTaskPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultBoolean>> {
        const queryParameters: any = {};

        if (requestParameters['taskId'] != null) {
            queryParameters['taskId'] = requestParameters['taskId'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['message'] != null) {
            queryParameters['message'] = requestParameters['message'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/oms/task/updateTask`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultBooleanFromJSON(jsonValue));
    }

    /**
     * 
     * 更新任务信息
     */
    async omsTaskUpdateTaskPost(requestParameters: OmsTaskUpdateTaskPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultBoolean> {
        const response = await this.omsTaskUpdateTaskPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
