/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ResultBaseQueryPageUserInfoVo,
  ResultBoolean,
  ResultString,
  ResultUserInfoVo,
  UserCreateInput,
  UserUpdateInput,
} from '../models/index';
import {
    ResultBaseQueryPageUserInfoVoFromJSON,
    ResultBaseQueryPageUserInfoVoToJSON,
    ResultBooleanFromJSON,
    ResultBooleanToJSON,
    ResultStringFromJSON,
    ResultStringToJSON,
    ResultUserInfoVoFromJSON,
    ResultUserInfoVoToJSON,
    UserCreateInputFromJSON,
    UserCreateInputToJSON,
    UserUpdateInputFromJSON,
    UserUpdateInputToJSON,
} from '../models/index';

export interface OmsUserCreatePostRequest {
    userCreateInput?: UserCreateInput;
}

export interface OmsUserDeleteUserIdPostRequest {
    userId: string;
}

export interface OmsUserListGetRequest {
    pageNo?: number;
    pageSize?: number;
    userId?: string;
    username?: string;
    email?: string;
    status?: number;
}

export interface OmsUserUpdatePostRequest {
    userUpdateInput?: UserUpdateInput;
}

export interface OmsUserUserIdGetRequest {
    userId: string;
}

/**
 * 
 */
export class OmsUserControllerApi extends runtime.BaseAPI {

    /**
     * 
     * 创建用户
     */
    async omsUserCreatePostRaw(requestParameters: OmsUserCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultString>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/oms/user/create`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserCreateInputToJSON(requestParameters['userCreateInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultStringFromJSON(jsonValue));
    }

    /**
     * 
     * 创建用户
     */
    async omsUserCreatePost(requestParameters: OmsUserCreatePostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultString> {
        const response = await this.omsUserCreatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * 删除用户
     */
    async omsUserDeleteUserIdPostRaw(requestParameters: OmsUserDeleteUserIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultBoolean>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling omsUserDeleteUserIdPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/oms/user/delete/{userId}`.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultBooleanFromJSON(jsonValue));
    }

    /**
     * 
     * 删除用户
     */
    async omsUserDeleteUserIdPost(requestParameters: OmsUserDeleteUserIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultBoolean> {
        const response = await this.omsUserDeleteUserIdPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * 分页查询用户列表
     */
    async omsUserListGetRaw(requestParameters: OmsUserListGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultBaseQueryPageUserInfoVo>> {
        const queryParameters: any = {};

        if (requestParameters['pageNo'] != null) {
            queryParameters['pageNo'] = requestParameters['pageNo'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['userId'] != null) {
            queryParameters['userId'] = requestParameters['userId'];
        }

        if (requestParameters['username'] != null) {
            queryParameters['username'] = requestParameters['username'];
        }

        if (requestParameters['email'] != null) {
            queryParameters['email'] = requestParameters['email'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/oms/user/list`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultBaseQueryPageUserInfoVoFromJSON(jsonValue));
    }

    /**
     * 
     * 分页查询用户列表
     */
    async omsUserListGet(requestParameters: OmsUserListGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultBaseQueryPageUserInfoVo> {
        const response = await this.omsUserListGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * 更新用户信息
     */
    async omsUserUpdatePostRaw(requestParameters: OmsUserUpdatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultString>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/oms/user/update`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserUpdateInputToJSON(requestParameters['userUpdateInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultStringFromJSON(jsonValue));
    }

    /**
     * 
     * 更新用户信息
     */
    async omsUserUpdatePost(requestParameters: OmsUserUpdatePostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultString> {
        const response = await this.omsUserUpdatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * 根据ID获取用户详情
     */
    async omsUserUserIdGetRaw(requestParameters: OmsUserUserIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultUserInfoVo>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling omsUserUserIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/oms/user/{userId}`.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultUserInfoVoFromJSON(jsonValue));
    }

    /**
     * 
     * 根据ID获取用户详情
     */
    async omsUserUserIdGet(requestParameters: OmsUserUserIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultUserInfoVo> {
        const response = await this.omsUserUserIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
