/* tslint:disable */
/* eslint-disable */
/**
 * 个人项目
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ResultBaseQueryPageLocalFileSimpleDto,
  ResultBaseQueryPageMmsNovelFile,
  ResultOmsJob,
  ResultString,
} from '../models/index';
import {
    ResultBaseQueryPageLocalFileSimpleDtoFromJSON,
    ResultBaseQueryPageLocalFileSimpleDtoToJSON,
    ResultBaseQueryPageMmsNovelFileFromJSON,
    ResultBaseQueryPageMmsNovelFileToJSON,
    ResultOmsJobFromJSON,
    ResultOmsJobToJSON,
    ResultStringFromJSON,
    ResultStringToJSON,
} from '../models/index';

export interface UmmsDownloadMaterialGetRequest {
    mmsNovelFileId?: string;
}

export interface UmmsLocalPageGetRequest {
    operator: string;
    pageNo?: number;
    pageSize?: number;
}

export interface UmmsNoevlPageGetRequest {
    operator: string;
    pageNo?: number;
    pageSize?: number;
    novelId?: number;
    fileName?: string;
}

export interface UmmsSyncMaterialGetRequest {
    operator: string;
    size?: number;
}

/**
 * 
 */
export class UMmsNovelControllerApi extends runtime.BaseAPI {

    /**
     * 
     * 文件去重
     */
    async ummsDedupPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultOmsJob>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/umms/dedup`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultOmsJobFromJSON(jsonValue));
    }

    /**
     * 
     * 文件去重
     */
    async ummsDedupPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultOmsJob> {
        const response = await this.ummsDedupPostRaw(initOverrides);
        return await response.value();
    }

    /**
     * 
     * 下载物料
     */
    async ummsDownloadMaterialGetRaw(requestParameters: UmmsDownloadMaterialGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<number>>> {
        const queryParameters: any = {};

        if (requestParameters['mmsNovelFileId'] != null) {
            queryParameters['mmsNovelFileId'] = requestParameters['mmsNovelFileId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/umms/downloadMaterial`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * 
     * 下载物料
     */
    async ummsDownloadMaterialGet(requestParameters: UmmsDownloadMaterialGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<number>> {
        const response = await this.ummsDownloadMaterialGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * 获取未处理的小说列表
     */
    async ummsLocalPageGetRaw(requestParameters: UmmsLocalPageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultBaseQueryPageLocalFileSimpleDto>> {
        if (requestParameters['operator'] == null) {
            throw new runtime.RequiredError(
                'operator',
                'Required parameter "operator" was null or undefined when calling ummsLocalPageGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['operator'] != null) {
            queryParameters['operator'] = requestParameters['operator'];
        }

        if (requestParameters['pageNo'] != null) {
            queryParameters['pageNo'] = requestParameters['pageNo'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/umms/local/page`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultBaseQueryPageLocalFileSimpleDtoFromJSON(jsonValue));
    }

    /**
     * 
     * 获取未处理的小说列表
     */
    async ummsLocalPageGet(requestParameters: UmmsLocalPageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultBaseQueryPageLocalFileSimpleDto> {
        const response = await this.ummsLocalPageGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * 查询物料分页列表
     */
    async ummsNoevlPageGetRaw(requestParameters: UmmsNoevlPageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultBaseQueryPageMmsNovelFile>> {
        if (requestParameters['operator'] == null) {
            throw new runtime.RequiredError(
                'operator',
                'Required parameter "operator" was null or undefined when calling ummsNoevlPageGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['operator'] != null) {
            queryParameters['operator'] = requestParameters['operator'];
        }

        if (requestParameters['pageNo'] != null) {
            queryParameters['pageNo'] = requestParameters['pageNo'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['novelId'] != null) {
            queryParameters['novelId'] = requestParameters['novelId'];
        }

        if (requestParameters['fileName'] != null) {
            queryParameters['fileName'] = requestParameters['fileName'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/umms/noevl/page`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultBaseQueryPageMmsNovelFileFromJSON(jsonValue));
    }

    /**
     * 
     * 查询物料分页列表
     */
    async ummsNoevlPageGet(requestParameters: UmmsNoevlPageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultBaseQueryPageMmsNovelFile> {
        const response = await this.ummsNoevlPageGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * 同步素材到 oos
     */
    async ummsSyncMaterialGetRaw(requestParameters: UmmsSyncMaterialGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultString>> {
        if (requestParameters['operator'] == null) {
            throw new runtime.RequiredError(
                'operator',
                'Required parameter "operator" was null or undefined when calling ummsSyncMaterialGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['operator'] != null) {
            queryParameters['operator'] = requestParameters['operator'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/umms/syncMaterial`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultStringFromJSON(jsonValue));
    }

    /**
     * 
     * 同步素材到 oos
     */
    async ummsSyncMaterialGet(requestParameters: UmmsSyncMaterialGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultString> {
        const response = await this.ummsSyncMaterialGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
