/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ResultBaseQueryPageWbTask,
  ResultBoolean,
  ResultListWbTask,
  ResultWbTask,
  WbTask,
  WbTaskPageInput,
} from '../models/index';
import {
    ResultBaseQueryPageWbTaskFromJSON,
    ResultBaseQueryPageWbTaskToJSON,
    ResultBooleanFromJSON,
    ResultBooleanToJSON,
    ResultListWbTaskFromJSON,
    ResultListWbTaskToJSON,
    ResultWbTaskFromJSON,
    ResultWbTaskToJSON,
    WbTaskFromJSON,
    WbTaskToJSON,
    WbTaskPageInputFromJSON,
    WbTaskPageInputToJSON,
} from '../models/index';

export interface WbAddPostRequest {
    wbTask?: WbTask;
}

export interface WbAddSubTaskPostRequest {
    wbTask?: WbTask;
}

export interface WbDeletePostRequest {
    requestBody?: Array<string>;
}

export interface WbGetGetRequest {
    id?: string;
}

export interface WbPagePostRequest {
    wbTaskPageInput?: WbTaskPageInput;
}

export interface WbSubTasksGetRequest {
    parentId?: string;
}

export interface WbUpdatePostRequest {
    wbTask?: WbTask;
}

/**
 * 
 */
export class WbTaskControllerApi extends runtime.BaseAPI {

    /**
     * 
     * 创建工作台任务
     */
    async wbAddPostRaw(requestParameters: WbAddPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultBoolean>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/wb/add`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WbTaskToJSON(requestParameters['wbTask']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultBooleanFromJSON(jsonValue));
    }

    /**
     * 
     * 创建工作台任务
     */
    async wbAddPost(requestParameters: WbAddPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultBoolean> {
        const response = await this.wbAddPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * 创建子任务
     */
    async wbAddSubTaskPostRaw(requestParameters: WbAddSubTaskPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultBoolean>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/wb/addSubTask`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WbTaskToJSON(requestParameters['wbTask']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultBooleanFromJSON(jsonValue));
    }

    /**
     * 
     * 创建子任务
     */
    async wbAddSubTaskPost(requestParameters: WbAddSubTaskPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultBoolean> {
        const response = await this.wbAddSubTaskPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * 删除工作台任务
     */
    async wbDeletePostRaw(requestParameters: WbDeletePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultBoolean>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/wb/delete`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultBooleanFromJSON(jsonValue));
    }

    /**
     * 
     * 删除工作台任务
     */
    async wbDeletePost(requestParameters: WbDeletePostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultBoolean> {
        const response = await this.wbDeletePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * 根据ID查询工作台任务详情
     */
    async wbGetGetRaw(requestParameters: WbGetGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultWbTask>> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/wb/get`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultWbTaskFromJSON(jsonValue));
    }

    /**
     * 
     * 根据ID查询工作台任务详情
     */
    async wbGetGet(requestParameters: WbGetGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultWbTask> {
        const response = await this.wbGetGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * 分页查询工作台任务列表
     */
    async wbPagePostRaw(requestParameters: WbPagePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultBaseQueryPageWbTask>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/wb/page`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WbTaskPageInputToJSON(requestParameters['wbTaskPageInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultBaseQueryPageWbTaskFromJSON(jsonValue));
    }

    /**
     * 
     * 分页查询工作台任务列表
     */
    async wbPagePost(requestParameters: WbPagePostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultBaseQueryPageWbTask> {
        const response = await this.wbPagePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * 查询指定父任务下的子任务列表
     */
    async wbSubTasksGetRaw(requestParameters: WbSubTasksGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultListWbTask>> {
        const queryParameters: any = {};

        if (requestParameters['parentId'] != null) {
            queryParameters['parentId'] = requestParameters['parentId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/wb/subTasks`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultListWbTaskFromJSON(jsonValue));
    }

    /**
     * 
     * 查询指定父任务下的子任务列表
     */
    async wbSubTasksGet(requestParameters: WbSubTasksGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultListWbTask> {
        const response = await this.wbSubTasksGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 
     * 更新工作台任务
     */
    async wbUpdatePostRaw(requestParameters: WbUpdatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultBoolean>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/wb/update`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WbTaskToJSON(requestParameters['wbTask']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResultBooleanFromJSON(jsonValue));
    }

    /**
     * 
     * 更新工作台任务
     */
    async wbUpdatePost(requestParameters: WbUpdatePostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultBoolean> {
        const response = await this.wbUpdatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
