<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>net.arctel</groupId>
        <artifactId>fyrn</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>fyrn-workbench</artifactId>
    <packaging>pom</packaging>

    <name>Workbench</name>
    <description>工作台</description>
    <modules>
        <module>wb-api</module>
        <module>wb-service</module>
        <module>wb-model</module>
    </modules>

    <properties>
        <wb.version>${project.version}</wb.version>
    </properties>



</project>