<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>net.arctel.platform</groupId>
        <artifactId>oms</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>oms-service</artifactId>
    <name>OMS - Service Layer</name>
    <description>OMS 服务层, 包含业务逻辑实现、应用服务等</description>

    <dependencies>
        <!-- OMS 内部依赖 -->
        <dependency>
            <groupId>net.arctel.platform</groupId>
            <artifactId>oms-common</artifactId>
        </dependency>
        <dependency>
            <groupId>net.arctel.platform</groupId>
            <artifactId>oms-api</artifactId>
        </dependency>
        <dependency>
            <groupId>net.arctel.platform</groupId>
            <artifactId>oms-infra</artifactId>
        </dependency>

        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>s3</artifactId>
        </dependency>

        <!-- 测试 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>
