/* tslint:disable */
/* eslint-disable */
/**
 * 个人项目
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddParameterInput
 */
export interface AddParameterInput {
    /**
     * 操作人
     * @type {string}
     * @memberof AddParameterInput
     */
    operator: string;
    /**
     * 主键
     * @type {number}
     * @memberof AddParameterInput
     */
    paramCode?: number;
    /**
     * 参数名称
     * @type {string}
     * @memberof AddParameterInput
     */
    paramName?: string;
    /**
     * 参数类型
     * @type {string}
     * @memberof AddParameterInput
     */
    kindCode?: string;
    /**
     * 参数值
     * @type {string}
     * @memberof AddParameterInput
     */
    paramValue?: string;
    /**
     * 参数描述
     * @type {string}
     * @memberof AddParameterInput
     */
    paramDesc?: string;
    /**
     * 是否启用
     * @type {number}
     * @memberof AddParameterInput
     */
    enabledFlag?: number;
}

/**
 * Check if a given object implements the AddParameterInput interface.
 */
export function instanceOfAddParameterInput(value: object): value is AddParameterInput {
    if (!('operator' in value) || value['operator'] === undefined) return false;
    return true;
}

export function AddParameterInputFromJSON(json: any): AddParameterInput {
    return AddParameterInputFromJSONTyped(json, false);
}

export function AddParameterInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddParameterInput {
    if (json == null) {
        return json;
    }
    return {
        
        'operator': json['operator'],
        'paramCode': json['paramCode'] == null ? undefined : json['paramCode'],
        'paramName': json['paramName'] == null ? undefined : json['paramName'],
        'kindCode': json['kindCode'] == null ? undefined : json['kindCode'],
        'paramValue': json['paramValue'] == null ? undefined : json['paramValue'],
        'paramDesc': json['paramDesc'] == null ? undefined : json['paramDesc'],
        'enabledFlag': json['enabledFlag'] == null ? undefined : json['enabledFlag'],
    };
}

export function AddParameterInputToJSON(json: any): AddParameterInput {
    return AddParameterInputToJSONTyped(json, false);
}

export function AddParameterInputToJSONTyped(value?: AddParameterInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'operator': value['operator'],
        'paramCode': value['paramCode'],
        'paramName': value['paramName'],
        'kindCode': value['kindCode'],
        'paramValue': value['paramValue'],
        'paramDesc': value['paramDesc'],
        'enabledFlag': value['enabledFlag'],
    };
}

