/* tslint:disable */
/* eslint-disable */
/**
 * 个人项目
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OmsJob } from './OmsJob';
import {
    OmsJobFromJSON,
    OmsJobFromJSONTyped,
    OmsJobToJSON,
    OmsJobToJSONTyped,
} from './OmsJob';

/**
 * 
 * @export
 * @interface BaseQueryPageOmsJob
 */
export interface BaseQueryPageOmsJob {
    /**
     * 
     * @type {number}
     * @memberof BaseQueryPageOmsJob
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseQueryPageOmsJob
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseQueryPageOmsJob
     */
    currentPage?: number;
    /**
     * 
     * @type {Array<OmsJob>}
     * @memberof BaseQueryPageOmsJob
     */
    rows?: Array<OmsJob>;
}

/**
 * Check if a given object implements the BaseQueryPageOmsJob interface.
 */
export function instanceOfBaseQueryPageOmsJob(value: object): value is BaseQueryPageOmsJob {
    return true;
}

export function BaseQueryPageOmsJobFromJSON(json: any): BaseQueryPageOmsJob {
    return BaseQueryPageOmsJobFromJSONTyped(json, false);
}

export function BaseQueryPageOmsJobFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseQueryPageOmsJob {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'] == null ? undefined : json['total'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'currentPage': json['currentPage'] == null ? undefined : json['currentPage'],
        'rows': json['rows'] == null ? undefined : ((json['rows'] as Array<any>).map(OmsJobFromJSON)),
    };
}

export function BaseQueryPageOmsJobToJSON(json: any): BaseQueryPageOmsJob {
    return BaseQueryPageOmsJobToJSONTyped(json, false);
}

export function BaseQueryPageOmsJobToJSONTyped(value?: BaseQueryPageOmsJob | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'pageSize': value['pageSize'],
        'currentPage': value['currentPage'],
        'rows': value['rows'] == null ? undefined : ((value['rows'] as Array<any>).map(OmsJobToJSON)),
    };
}

