/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OmsParameter } from './OmsParameter';
import {
    OmsParameterFromJSON,
    OmsParameterFromJSONTyped,
    OmsParameterToJSON,
    OmsParameterToJSONTyped,
} from './OmsParameter';

/**
 * 
 * @export
 * @interface BaseQueryPageOmsParameter
 */
export interface BaseQueryPageOmsParameter {
    /**
     * 
     * @type {number}
     * @memberof BaseQueryPageOmsParameter
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseQueryPageOmsParameter
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseQueryPageOmsParameter
     */
    currentPage?: number;
    /**
     * 
     * @type {Array<OmsParameter>}
     * @memberof BaseQueryPageOmsParameter
     */
    rows?: Array<OmsParameter>;
}

/**
 * Check if a given object implements the BaseQueryPageOmsParameter interface.
 */
export function instanceOfBaseQueryPageOmsParameter(value: object): value is BaseQueryPageOmsParameter {
    return true;
}

export function BaseQueryPageOmsParameterFromJSON(json: any): BaseQueryPageOmsParameter {
    return BaseQueryPageOmsParameterFromJSONTyped(json, false);
}

export function BaseQueryPageOmsParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseQueryPageOmsParameter {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'] == null ? undefined : json['total'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'currentPage': json['currentPage'] == null ? undefined : json['currentPage'],
        'rows': json['rows'] == null ? undefined : ((json['rows'] as Array<any>).map(OmsParameterFromJSON)),
    };
}

export function BaseQueryPageOmsParameterToJSON(json: any): BaseQueryPageOmsParameter {
    return BaseQueryPageOmsParameterToJSONTyped(json, false);
}

export function BaseQueryPageOmsParameterToJSONTyped(value?: BaseQueryPageOmsParameter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'pageSize': value['pageSize'],
        'currentPage': value['currentPage'],
        'rows': value['rows'] == null ? undefined : ((value['rows'] as Array<any>).map(OmsParameterToJSON)),
    };
}

