/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OmsTask } from './OmsTask';
import {
    OmsTaskFromJSON,
    OmsTaskFromJSONTyped,
    OmsTaskToJSON,
    OmsTaskToJSONTyped,
} from './OmsTask';

/**
 * 
 * @export
 * @interface BaseQueryPageOmsTask
 */
export interface BaseQueryPageOmsTask {
    /**
     * 
     * @type {number}
     * @memberof BaseQueryPageOmsTask
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseQueryPageOmsTask
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseQueryPageOmsTask
     */
    currentPage?: number;
    /**
     * 
     * @type {Array<OmsTask>}
     * @memberof BaseQueryPageOmsTask
     */
    rows?: Array<OmsTask>;
}

/**
 * Check if a given object implements the BaseQueryPageOmsTask interface.
 */
export function instanceOfBaseQueryPageOmsTask(value: object): value is BaseQueryPageOmsTask {
    return true;
}

export function BaseQueryPageOmsTaskFromJSON(json: any): BaseQueryPageOmsTask {
    return BaseQueryPageOmsTaskFromJSONTyped(json, false);
}

export function BaseQueryPageOmsTaskFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseQueryPageOmsTask {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'] == null ? undefined : json['total'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'currentPage': json['currentPage'] == null ? undefined : json['currentPage'],
        'rows': json['rows'] == null ? undefined : ((json['rows'] as Array<any>).map(OmsTaskFromJSON)),
    };
}

export function BaseQueryPageOmsTaskToJSON(json: any): BaseQueryPageOmsTask {
    return BaseQueryPageOmsTaskToJSONTyped(json, false);
}

export function BaseQueryPageOmsTaskToJSONTyped(value?: BaseQueryPageOmsTask | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'pageSize': value['pageSize'],
        'currentPage': value['currentPage'],
        'rows': value['rows'] == null ? undefined : ((value['rows'] as Array<any>).map(OmsTaskToJSON)),
    };
}

