/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MmsNovel } from './MmsNovel';
import {
    MmsNovelFromJSON,
    MmsNovelFromJSONTyped,
    MmsNovelToJSON,
    MmsNovelToJSONTyped,
} from './MmsNovel';

/**
 * 
 * @export
 * @interface BaseQueryPageMmsNovel
 */
export interface BaseQueryPageMmsNovel {
    /**
     * 
     * @type {number}
     * @memberof BaseQueryPageMmsNovel
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseQueryPageMmsNovel
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseQueryPageMmsNovel
     */
    currentPage?: number;
    /**
     * 
     * @type {Array<MmsNovel>}
     * @memberof BaseQueryPageMmsNovel
     */
    rows?: Array<MmsNovel>;
}

/**
 * Check if a given object implements the BaseQueryPageMmsNovel interface.
 */
export function instanceOfBaseQueryPageMmsNovel(value: object): value is BaseQueryPageMmsNovel {
    return true;
}

export function BaseQueryPageMmsNovelFromJSON(json: any): BaseQueryPageMmsNovel {
    return BaseQueryPageMmsNovelFromJSONTyped(json, false);
}

export function BaseQueryPageMmsNovelFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseQueryPageMmsNovel {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'] == null ? undefined : json['total'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'currentPage': json['currentPage'] == null ? undefined : json['currentPage'],
        'rows': json['rows'] == null ? undefined : ((json['rows'] as Array<any>).map(MmsNovelFromJSON)),
    };
}

export function BaseQueryPageMmsNovelToJSON(json: any): BaseQueryPageMmsNovel {
    return BaseQueryPageMmsNovelToJSONTyped(json, false);
}

export function BaseQueryPageMmsNovelToJSONTyped(value?: BaseQueryPageMmsNovel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'pageSize': value['pageSize'],
        'currentPage': value['currentPage'],
        'rows': value['rows'] == null ? undefined : ((value['rows'] as Array<any>).map(MmsNovelToJSON)),
    };
}

