/* tslint:disable */
/* eslint-disable */
/**
 * 个人项目
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LocalFileSimpleDto } from './LocalFileSimpleDto';
import {
    LocalFileSimpleDtoFromJSON,
    LocalFileSimpleDtoFromJSONTyped,
    LocalFileSimpleDtoToJSON,
    LocalFileSimpleDtoToJSONTyped,
} from './LocalFileSimpleDto';

/**
 * 
 * @export
 * @interface BaseQueryPageLocalFileSimpleDto
 */
export interface BaseQueryPageLocalFileSimpleDto {
    /**
     * 
     * @type {number}
     * @memberof BaseQueryPageLocalFileSimpleDto
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseQueryPageLocalFileSimpleDto
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseQueryPageLocalFileSimpleDto
     */
    currentPage?: number;
    /**
     * 
     * @type {Array<LocalFileSimpleDto>}
     * @memberof BaseQueryPageLocalFileSimpleDto
     */
    rows?: Array<LocalFileSimpleDto>;
}

/**
 * Check if a given object implements the BaseQueryPageLocalFileSimpleDto interface.
 */
export function instanceOfBaseQueryPageLocalFileSimpleDto(value: object): value is BaseQueryPageLocalFileSimpleDto {
    return true;
}

export function BaseQueryPageLocalFileSimpleDtoFromJSON(json: any): BaseQueryPageLocalFileSimpleDto {
    return BaseQueryPageLocalFileSimpleDtoFromJSONTyped(json, false);
}

export function BaseQueryPageLocalFileSimpleDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseQueryPageLocalFileSimpleDto {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'] == null ? undefined : json['total'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'currentPage': json['currentPage'] == null ? undefined : json['currentPage'],
        'rows': json['rows'] == null ? undefined : ((json['rows'] as Array<any>).map(LocalFileSimpleDtoFromJSON)),
    };
}

export function BaseQueryPageLocalFileSimpleDtoToJSON(json: any): BaseQueryPageLocalFileSimpleDto {
    return BaseQueryPageLocalFileSimpleDtoToJSONTyped(json, false);
}

export function BaseQueryPageLocalFileSimpleDtoToJSONTyped(value?: BaseQueryPageLocalFileSimpleDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'pageSize': value['pageSize'],
        'currentPage': value['currentPage'],
        'rows': value['rows'] == null ? undefined : ((value['rows'] as Array<any>).map(LocalFileSimpleDtoToJSON)),
    };
}

