/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WbTask } from './WbTask';
import {
    WbTaskFromJSON,
    WbTaskFromJSONTyped,
    WbTaskToJSON,
    WbTaskToJSONTyped,
} from './WbTask';

/**
 * 
 * @export
 * @interface BaseQueryPageWbTask
 */
export interface BaseQueryPageWbTask {
    /**
     * 
     * @type {number}
     * @memberof BaseQueryPageWbTask
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseQueryPageWbTask
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseQueryPageWbTask
     */
    currentPage?: number;
    /**
     * 
     * @type {Array<WbTask>}
     * @memberof BaseQueryPageWbTask
     */
    rows?: Array<WbTask>;
}

/**
 * Check if a given object implements the BaseQueryPageWbTask interface.
 */
export function instanceOfBaseQueryPageWbTask(value: object): value is BaseQueryPageWbTask {
    return true;
}

export function BaseQueryPageWbTaskFromJSON(json: any): BaseQueryPageWbTask {
    return BaseQueryPageWbTaskFromJSONTyped(json, false);
}

export function BaseQueryPageWbTaskFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseQueryPageWbTask {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'] == null ? undefined : json['total'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'currentPage': json['currentPage'] == null ? undefined : json['currentPage'],
        'rows': json['rows'] == null ? undefined : ((json['rows'] as Array<any>).map(WbTaskFromJSON)),
    };
}

export function BaseQueryPageWbTaskToJSON(json: any): BaseQueryPageWbTask {
    return BaseQueryPageWbTaskToJSONTyped(json, false);
}

export function BaseQueryPageWbTaskToJSONTyped(value?: BaseQueryPageWbTask | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'pageSize': value['pageSize'],
        'currentPage': value['currentPage'],
        'rows': value['rows'] == null ? undefined : ((value['rows'] as Array<any>).map(WbTaskToJSON)),
    };
}

