/* tslint:disable */
/* eslint-disable */
/**
 * 个人项目
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MmsNovelFile } from './MmsNovelFile';
import {
    MmsNovelFileFromJSON,
    MmsNovelFileFromJSONTyped,
    MmsNovelFileToJSON,
    MmsNovelFileToJSONTyped,
} from './MmsNovelFile';

/**
 * 
 * @export
 * @interface BaseQueryPageMmsNovelFile
 */
export interface BaseQueryPageMmsNovelFile {
    /**
     * 
     * @type {number}
     * @memberof BaseQueryPageMmsNovelFile
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseQueryPageMmsNovelFile
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseQueryPageMmsNovelFile
     */
    currentPage?: number;
    /**
     * 
     * @type {Array<MmsNovelFile>}
     * @memberof BaseQueryPageMmsNovelFile
     */
    rows?: Array<MmsNovelFile>;
}

/**
 * Check if a given object implements the BaseQueryPageMmsNovelFile interface.
 */
export function instanceOfBaseQueryPageMmsNovelFile(value: object): value is BaseQueryPageMmsNovelFile {
    return true;
}

export function BaseQueryPageMmsNovelFileFromJSON(json: any): BaseQueryPageMmsNovelFile {
    return BaseQueryPageMmsNovelFileFromJSONTyped(json, false);
}

export function BaseQueryPageMmsNovelFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseQueryPageMmsNovelFile {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'] == null ? undefined : json['total'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'currentPage': json['currentPage'] == null ? undefined : json['currentPage'],
        'rows': json['rows'] == null ? undefined : ((json['rows'] as Array<any>).map(MmsNovelFileFromJSON)),
    };
}

export function BaseQueryPageMmsNovelFileToJSON(json: any): BaseQueryPageMmsNovelFile {
    return BaseQueryPageMmsNovelFileToJSONTyped(json, false);
}

export function BaseQueryPageMmsNovelFileToJSONTyped(value?: BaseQueryPageMmsNovelFile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'pageSize': value['pageSize'],
        'currentPage': value['currentPage'],
        'rows': value['rows'] == null ? undefined : ((value['rows'] as Array<any>).map(MmsNovelFileToJSON)),
    };
}

