/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MmsMeta } from './MmsMeta';
import {
    MmsMetaFromJSON,
    MmsMetaFromJSONTyped,
    MmsMetaToJSON,
    MmsMetaToJSONTyped,
} from './MmsMeta';

/**
 * 
 * @export
 * @interface BaseQueryPageMmsMeta
 */
export interface BaseQueryPageMmsMeta {
    /**
     * 
     * @type {number}
     * @memberof BaseQueryPageMmsMeta
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseQueryPageMmsMeta
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseQueryPageMmsMeta
     */
    currentPage?: number;
    /**
     * 
     * @type {Array<MmsMeta>}
     * @memberof BaseQueryPageMmsMeta
     */
    rows?: Array<MmsMeta>;
}

/**
 * Check if a given object implements the BaseQueryPageMmsMeta interface.
 */
export function instanceOfBaseQueryPageMmsMeta(value: object): value is BaseQueryPageMmsMeta {
    return true;
}

export function BaseQueryPageMmsMetaFromJSON(json: any): BaseQueryPageMmsMeta {
    return BaseQueryPageMmsMetaFromJSONTyped(json, false);
}

export function BaseQueryPageMmsMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseQueryPageMmsMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'] == null ? undefined : json['total'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'currentPage': json['currentPage'] == null ? undefined : json['currentPage'],
        'rows': json['rows'] == null ? undefined : ((json['rows'] as Array<any>).map(MmsMetaFromJSON)),
    };
}

export function BaseQueryPageMmsMetaToJSON(json: any): BaseQueryPageMmsMeta {
    return BaseQueryPageMmsMetaToJSONTyped(json, false);
}

export function BaseQueryPageMmsMetaToJSONTyped(value?: BaseQueryPageMmsMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'pageSize': value['pageSize'],
        'currentPage': value['currentPage'],
        'rows': value['rows'] == null ? undefined : ((value['rows'] as Array<any>).map(MmsMetaToJSON)),
    };
}

