/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserInfoVo } from './UserInfoVo';
import {
    UserInfoVoFromJSON,
    UserInfoVoFromJSONTyped,
    UserInfoVoToJSON,
    UserInfoVoToJSONTyped,
} from './UserInfoVo';

/**
 * 
 * @export
 * @interface BaseQueryPageUserInfoVo
 */
export interface BaseQueryPageUserInfoVo {
    /**
     * 
     * @type {number}
     * @memberof BaseQueryPageUserInfoVo
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseQueryPageUserInfoVo
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseQueryPageUserInfoVo
     */
    currentPage?: number;
    /**
     * 
     * @type {Array<UserInfoVo>}
     * @memberof BaseQueryPageUserInfoVo
     */
    rows?: Array<UserInfoVo>;
}

/**
 * Check if a given object implements the BaseQueryPageUserInfoVo interface.
 */
export function instanceOfBaseQueryPageUserInfoVo(value: object): value is BaseQueryPageUserInfoVo {
    return true;
}

export function BaseQueryPageUserInfoVoFromJSON(json: any): BaseQueryPageUserInfoVo {
    return BaseQueryPageUserInfoVoFromJSONTyped(json, false);
}

export function BaseQueryPageUserInfoVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseQueryPageUserInfoVo {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'] == null ? undefined : json['total'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'currentPage': json['currentPage'] == null ? undefined : json['currentPage'],
        'rows': json['rows'] == null ? undefined : ((json['rows'] as Array<any>).map(UserInfoVoFromJSON)),
    };
}

export function BaseQueryPageUserInfoVoToJSON(json: any): BaseQueryPageUserInfoVo {
    return BaseQueryPageUserInfoVoToJSONTyped(json, false);
}

export function BaseQueryPageUserInfoVoToJSONTyped(value?: BaseQueryPageUserInfoVo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'pageSize': value['pageSize'],
        'currentPage': value['currentPage'],
        'rows': value['rows'] == null ? undefined : ((value['rows'] as Array<any>).map(UserInfoVoToJSON)),
    };
}

