/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobProgressDto } from './JobProgressDto';
import {
    JobProgressDtoFromJSON,
    JobProgressDtoFromJSONTyped,
    JobProgressDtoToJSON,
    JobProgressDtoToJSONTyped,
} from './JobProgressDto';

/**
 * 
 * @export
 * @interface JobDetailOutput
 */
export interface JobDetailOutput {
    /**
     * 业务任务ID
     * @type {string}
     * @memberof JobDetailOutput
     */
    jobId?: string;
    /**
     * 任务类型，如 file_batch
     * @type {string}
     * @memberof JobDetailOutput
     */
    taskType?: string;
    /**
     * 0=queued,1=running,2=success,3=failed,4=canceled
     * @type {number}
     * @memberof JobDetailOutput
     */
    status?: number;
    /**
     * 状态说明/失败摘要
     * @type {string}
     * @memberof JobDetailOutput
     */
    message?: string;
    /**
     * 触发人
     * @type {string}
     * @memberof JobDetailOutput
     */
    createdUser?: string;
    /**
     * 任务开始时间
     * @type {string}
     * @memberof JobDetailOutput
     */
    startedTime?: string;
    /**
     * 任务结束时间
     * @type {string}
     * @memberof JobDetailOutput
     */
    finishedTime?: string;
    /**
     * 创建时间
     * @type {string}
     * @memberof JobDetailOutput
     */
    createTime?: string;
    /**
     * 修改时间
     * @type {string}
     * @memberof JobDetailOutput
     */
    updateTime?: string;
    /**
     * 
     * @type {JobProgressDto}
     * @memberof JobDetailOutput
     */
    jobProgressDTO?: JobProgressDto;
    /**
     * 
     * @type {string}
     * @memberof JobDetailOutput
     */
    jobLog?: string;
}

/**
 * Check if a given object implements the JobDetailOutput interface.
 */
export function instanceOfJobDetailOutput(value: object): value is JobDetailOutput {
    return true;
}

export function JobDetailOutputFromJSON(json: any): JobDetailOutput {
    return JobDetailOutputFromJSONTyped(json, false);
}

export function JobDetailOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobDetailOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'jobId': json['jobId'] == null ? undefined : json['jobId'],
        'taskType': json['taskType'] == null ? undefined : json['taskType'],
        'status': json['status'] == null ? undefined : json['status'],
        'message': json['message'] == null ? undefined : json['message'],
        'createdUser': json['createdUser'] == null ? undefined : json['createdUser'],
        'startedTime': json['startedTime'] == null ? undefined : json['startedTime'],
        'finishedTime': json['finishedTime'] == null ? undefined : json['finishedTime'],
        'createTime': json['createTime'] == null ? undefined : json['createTime'],
        'updateTime': json['updateTime'] == null ? undefined : json['updateTime'],
        'jobProgressDTO': json['jobProgressDTO'] == null ? undefined : JobProgressDtoFromJSON(json['jobProgressDTO']),
        'jobLog': json['jobLog'] == null ? undefined : json['jobLog'],
    };
}

export function JobDetailOutputToJSON(json: any): JobDetailOutput {
    return JobDetailOutputToJSONTyped(json, false);
}

export function JobDetailOutputToJSONTyped(value?: JobDetailOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jobId': value['jobId'],
        'taskType': value['taskType'],
        'status': value['status'],
        'message': value['message'],
        'createdUser': value['createdUser'],
        'startedTime': value['startedTime'],
        'finishedTime': value['finishedTime'],
        'createTime': value['createTime'],
        'updateTime': value['updateTime'],
        'jobProgressDTO': JobProgressDtoToJSON(value['jobProgressDTO']),
        'jobLog': value['jobLog'],
    };
}

