/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ThreadPoolMetricsDto } from './ThreadPoolMetricsDto';
import {
    ThreadPoolMetricsDtoFromJSON,
    ThreadPoolMetricsDtoFromJSONTyped,
    ThreadPoolMetricsDtoToJSON,
    ThreadPoolMetricsDtoToJSONTyped,
} from './ThreadPoolMetricsDto';
import type { JobOverviewDto } from './JobOverviewDto';
import {
    JobOverviewDtoFromJSON,
    JobOverviewDtoFromJSONTyped,
    JobOverviewDtoToJSON,
    JobOverviewDtoToJSONTyped,
} from './JobOverviewDto';

/**
 * 
 * @export
 * @interface JobMonitorOutput
 */
export interface JobMonitorOutput {
    /**
     * 
     * @type {ThreadPoolMetricsDto}
     * @memberof JobMonitorOutput
     */
    threadPoolMetricsDTO?: ThreadPoolMetricsDto;
    /**
     * 
     * @type {JobOverviewDto}
     * @memberof JobMonitorOutput
     */
    jobOverviewDto?: JobOverviewDto;
}

/**
 * Check if a given object implements the JobMonitorOutput interface.
 */
export function instanceOfJobMonitorOutput(value: object): value is JobMonitorOutput {
    return true;
}

export function JobMonitorOutputFromJSON(json: any): JobMonitorOutput {
    return JobMonitorOutputFromJSONTyped(json, false);
}

export function JobMonitorOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobMonitorOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'threadPoolMetricsDTO': json['threadPoolMetricsDTO'] == null ? undefined : ThreadPoolMetricsDtoFromJSON(json['threadPoolMetricsDTO']),
        'jobOverviewDto': json['jobOverviewDto'] == null ? undefined : JobOverviewDtoFromJSON(json['jobOverviewDto']),
    };
}

export function JobMonitorOutputToJSON(json: any): JobMonitorOutput {
    return JobMonitorOutputToJSONTyped(json, false);
}

export function JobMonitorOutputToJSONTyped(value?: JobMonitorOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'threadPoolMetricsDTO': ThreadPoolMetricsDtoToJSON(value['threadPoolMetricsDTO']),
        'jobOverviewDto': JobOverviewDtoToJSON(value['jobOverviewDto']),
    };
}

