/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JobOverviewDto
 */
export interface JobOverviewDto {
    /**
     * 
     * @type {number}
     * @memberof JobOverviewDto
     */
    totalJobCount?: number;
    /**
     * 
     * @type {number}
     * @memberof JobOverviewDto
     */
    runningJobCount?: number;
    /**
     * 
     * @type {number}
     * @memberof JobOverviewDto
     */
    successJobCount?: number;
    /**
     * 
     * @type {number}
     * @memberof JobOverviewDto
     */
    failedJobCount?: number;
}

/**
 * Check if a given object implements the JobOverviewDto interface.
 */
export function instanceOfJobOverviewDto(value: object): value is JobOverviewDto {
    return true;
}

export function JobOverviewDtoFromJSON(json: any): JobOverviewDto {
    return JobOverviewDtoFromJSONTyped(json, false);
}

export function JobOverviewDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobOverviewDto {
    if (json == null) {
        return json;
    }
    return {
        
        'totalJobCount': json['totalJobCount'] == null ? undefined : json['totalJobCount'],
        'runningJobCount': json['runningJobCount'] == null ? undefined : json['runningJobCount'],
        'successJobCount': json['successJobCount'] == null ? undefined : json['successJobCount'],
        'failedJobCount': json['failedJobCount'] == null ? undefined : json['failedJobCount'],
    };
}

export function JobOverviewDtoToJSON(json: any): JobOverviewDto {
    return JobOverviewDtoToJSONTyped(json, false);
}

export function JobOverviewDtoToJSONTyped(value?: JobOverviewDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalJobCount': value['totalJobCount'],
        'runningJobCount': value['runningJobCount'],
        'successJobCount': value['successJobCount'],
        'failedJobCount': value['failedJobCount'],
    };
}

