/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JobProgressDto
 */
export interface JobProgressDto {
    /**
     * 
     * @type {number}
     * @memberof JobProgressDto
     */
    current?: number;
    /**
     * 
     * @type {number}
     * @memberof JobProgressDto
     */
    total?: number;
}

/**
 * Check if a given object implements the JobProgressDto interface.
 */
export function instanceOfJobProgressDto(value: object): value is JobProgressDto {
    return true;
}

export function JobProgressDtoFromJSON(json: any): JobProgressDto {
    return JobProgressDtoFromJSONTyped(json, false);
}

export function JobProgressDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobProgressDto {
    if (json == null) {
        return json;
    }
    return {
        
        'current': json['current'] == null ? undefined : json['current'],
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function JobProgressDtoToJSON(json: any): JobProgressDto {
    return JobProgressDtoToJSONTyped(json, false);
}

export function JobProgressDtoToJSONTyped(value?: JobProgressDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'current': value['current'],
        'total': value['total'],
    };
}

