/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LocalFileSimpleDto
 */
export interface LocalFileSimpleDto {
    /**
     * 文件名称
     * @type {string}
     * @memberof LocalFileSimpleDto
     */
    fileName?: string;
    /**
     * 文件路径
     * @type {string}
     * @memberof LocalFileSimpleDto
     */
    filePath?: string;
    /**
     * 文件大小，单位：字节
     * @type {number}
     * @memberof LocalFileSimpleDto
     */
    fileSize?: number;
    /**
     * 小说字数, 单位：字
     * @type {number}
     * @memberof LocalFileSimpleDto
     */
    wordCount?: number;
}

/**
 * Check if a given object implements the LocalFileSimpleDto interface.
 */
export function instanceOfLocalFileSimpleDto(value: object): value is LocalFileSimpleDto {
    return true;
}

export function LocalFileSimpleDtoFromJSON(json: any): LocalFileSimpleDto {
    return LocalFileSimpleDtoFromJSONTyped(json, false);
}

export function LocalFileSimpleDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocalFileSimpleDto {
    if (json == null) {
        return json;
    }
    return {
        
        'fileName': json['fileName'] == null ? undefined : json['fileName'],
        'filePath': json['filePath'] == null ? undefined : json['filePath'],
        'fileSize': json['fileSize'] == null ? undefined : json['fileSize'],
        'wordCount': json['wordCount'] == null ? undefined : json['wordCount'],
    };
}

export function LocalFileSimpleDtoToJSON(json: any): LocalFileSimpleDto {
    return LocalFileSimpleDtoToJSONTyped(json, false);
}

export function LocalFileSimpleDtoToJSONTyped(value?: LocalFileSimpleDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fileName': value['fileName'],
        'filePath': value['filePath'],
        'fileSize': value['fileSize'],
        'wordCount': value['wordCount'],
    };
}

