/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MmsMeta
 */
export interface MmsMeta {
    /**
     * 主键
     * @type {number}
     * @memberof MmsMeta
     */
    id?: number;
    /**
     * Platform Book Number
     * @type {string}
     * @memberof MmsMeta
     */
    pbn?: string;
    /**
     * 小说名称
     * @type {string}
     * @memberof MmsMeta
     */
    title?: string;
    /**
     * 小说作者
     * @type {string}
     * @memberof MmsMeta
     */
    author?: string;
    /**
     * 小说标签
     * @type {string}
     * @memberof MmsMeta
     */
    tag?: string;
    /**
     * 小说简介
     * @type {string}
     * @memberof MmsMeta
     */
    summary?: string;
    /**
     * 小说人气值
     * @type {number}
     * @memberof MmsMeta
     */
    popularity?: number;
    /**
     * 小说字数, 单位：字
     * @type {number}
     * @memberof MmsMeta
     */
    wordCount?: number;
    /**
     * 1: 连载中, 2：完结
     * @type {number}
     * @memberof MmsMeta
     */
    status?: number;
    /**
     * 小说来源
     * @type {string}
     * @memberof MmsMeta
     */
    source?: string;
    /**
     * 小说来源链接
     * @type {string}
     * @memberof MmsMeta
     */
    sourceUrl?: string;
    /**
     * 小说发布时间
     * @type {string}
     * @memberof MmsMeta
     */
    postTime?: string;
    /**
     * 小说最后编辑时间
     * @type {string}
     * @memberof MmsMeta
     */
    editTime?: string;
    /**
     * 创建时间
     * @type {string}
     * @memberof MmsMeta
     */
    createTime?: string;
    /**
     * 修改时间
     * @type {string}
     * @memberof MmsMeta
     */
    updateTime?: string;
    /**
     * 创建人
     * @type {string}
     * @memberof MmsMeta
     */
    createdUser?: string;
    /**
     * 修改人
     * @type {string}
     * @memberof MmsMeta
     */
    updatedUser?: string;
}

/**
 * Check if a given object implements the MmsMeta interface.
 */
export function instanceOfMmsMeta(value: object): value is MmsMeta {
    return true;
}

export function MmsMetaFromJSON(json: any): MmsMeta {
    return MmsMetaFromJSONTyped(json, false);
}

export function MmsMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): MmsMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'pbn': json['pbn'] == null ? undefined : json['pbn'],
        'title': json['title'] == null ? undefined : json['title'],
        'author': json['author'] == null ? undefined : json['author'],
        'tag': json['tag'] == null ? undefined : json['tag'],
        'summary': json['summary'] == null ? undefined : json['summary'],
        'popularity': json['popularity'] == null ? undefined : json['popularity'],
        'wordCount': json['wordCount'] == null ? undefined : json['wordCount'],
        'status': json['status'] == null ? undefined : json['status'],
        'source': json['source'] == null ? undefined : json['source'],
        'sourceUrl': json['sourceUrl'] == null ? undefined : json['sourceUrl'],
        'postTime': json['postTime'] == null ? undefined : json['postTime'],
        'editTime': json['editTime'] == null ? undefined : json['editTime'],
        'createTime': json['createTime'] == null ? undefined : json['createTime'],
        'updateTime': json['updateTime'] == null ? undefined : json['updateTime'],
        'createdUser': json['createdUser'] == null ? undefined : json['createdUser'],
        'updatedUser': json['updatedUser'] == null ? undefined : json['updatedUser'],
    };
}

export function MmsMetaToJSON(json: any): MmsMeta {
    return MmsMetaToJSONTyped(json, false);
}

export function MmsMetaToJSONTyped(value?: MmsMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'pbn': value['pbn'],
        'title': value['title'],
        'author': value['author'],
        'tag': value['tag'],
        'summary': value['summary'],
        'popularity': value['popularity'],
        'wordCount': value['wordCount'],
        'status': value['status'],
        'source': value['source'],
        'sourceUrl': value['sourceUrl'],
        'postTime': value['postTime'],
        'editTime': value['editTime'],
        'createTime': value['createTime'],
        'updateTime': value['updateTime'],
        'createdUser': value['createdUser'],
        'updatedUser': value['updatedUser'],
    };
}

