/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MmsNovelFile
 */
export interface MmsNovelFile {
    /**
     * 主键
     * @type {string}
     * @memberof MmsNovelFile
     */
    id?: string;
    /**
     * 小说ID
     * @type {string}
     * @memberof MmsNovelFile
     */
    novelId?: string;
    /**
     * 文件名称
     * @type {string}
     * @memberof MmsNovelFile
     */
    fileName?: string;
    /**
     * 文件路径
     * @type {string}
     * @memberof MmsNovelFile
     */
    filePath?: string;
    /**
     * 文件大小，单位：字节
     * @type {number}
     * @memberof MmsNovelFile
     */
    fileSize?: number;
    /**
     * 小说字数, 单位：字
     * @type {number}
     * @memberof MmsNovelFile
     */
    wordCount?: number;
    /**
     * 2：正常，4：删除
     * @type {number}
     * @memberof MmsNovelFile
     */
    status?: number;
    /**
     * 创建时间
     * @type {string}
     * @memberof MmsNovelFile
     */
    createTime?: string;
    /**
     * 修改时间
     * @type {string}
     * @memberof MmsNovelFile
     */
    updateTime?: string;
    /**
     * 创建人
     * @type {string}
     * @memberof MmsNovelFile
     */
    createdUser?: string;
    /**
     * 修改人
     * @type {string}
     * @memberof MmsNovelFile
     */
    updatedUser?: string;
}

/**
 * Check if a given object implements the MmsNovelFile interface.
 */
export function instanceOfMmsNovelFile(value: object): value is MmsNovelFile {
    return true;
}

export function MmsNovelFileFromJSON(json: any): MmsNovelFile {
    return MmsNovelFileFromJSONTyped(json, false);
}

export function MmsNovelFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): MmsNovelFile {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'novelId': json['novelId'] == null ? undefined : json['novelId'],
        'fileName': json['fileName'] == null ? undefined : json['fileName'],
        'filePath': json['filePath'] == null ? undefined : json['filePath'],
        'fileSize': json['fileSize'] == null ? undefined : json['fileSize'],
        'wordCount': json['wordCount'] == null ? undefined : json['wordCount'],
        'status': json['status'] == null ? undefined : json['status'],
        'createTime': json['createTime'] == null ? undefined : json['createTime'],
        'updateTime': json['updateTime'] == null ? undefined : json['updateTime'],
        'createdUser': json['createdUser'] == null ? undefined : json['createdUser'],
        'updatedUser': json['updatedUser'] == null ? undefined : json['updatedUser'],
    };
}

export function MmsNovelFileToJSON(json: any): MmsNovelFile {
    return MmsNovelFileToJSONTyped(json, false);
}

export function MmsNovelFileToJSONTyped(value?: MmsNovelFile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'novelId': value['novelId'],
        'fileName': value['fileName'],
        'filePath': value['filePath'],
        'fileSize': value['fileSize'],
        'wordCount': value['wordCount'],
        'status': value['status'],
        'createTime': value['createTime'],
        'updateTime': value['updateTime'],
        'createdUser': value['createdUser'],
        'updatedUser': value['updatedUser'],
    };
}

