/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MmsNovel
 */
export interface MmsNovel {
    /**
     * 主键
     * @type {string}
     * @memberof MmsNovel
     */
    id?: string;
    /**
     * 小说名称
     * @type {string}
     * @memberof MmsNovel
     */
    novelTitle?: string;
    /**
     * 小说作者
     * @type {string}
     * @memberof MmsNovel
     */
    novelAuthor?: string;
    /**
     * 2：正常，4：删除
     * @type {number}
     * @memberof MmsNovel
     */
    status?: number;
    /**
     * 创建时间
     * @type {string}
     * @memberof MmsNovel
     */
    createTime?: string;
    /**
     * 修改时间
     * @type {string}
     * @memberof MmsNovel
     */
    updateTime?: string;
    /**
     * 创建人
     * @type {string}
     * @memberof MmsNovel
     */
    createdUser?: string;
    /**
     * 修改人
     * @type {string}
     * @memberof MmsNovel
     */
    updatedUser?: string;
}

/**
 * Check if a given object implements the MmsNovel interface.
 */
export function instanceOfMmsNovel(value: object): value is MmsNovel {
    return true;
}

export function MmsNovelFromJSON(json: any): MmsNovel {
    return MmsNovelFromJSONTyped(json, false);
}

export function MmsNovelFromJSONTyped(json: any, ignoreDiscriminator: boolean): MmsNovel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'novelTitle': json['novelTitle'] == null ? undefined : json['novelTitle'],
        'novelAuthor': json['novelAuthor'] == null ? undefined : json['novelAuthor'],
        'status': json['status'] == null ? undefined : json['status'],
        'createTime': json['createTime'] == null ? undefined : json['createTime'],
        'updateTime': json['updateTime'] == null ? undefined : json['updateTime'],
        'createdUser': json['createdUser'] == null ? undefined : json['createdUser'],
        'updatedUser': json['updatedUser'] == null ? undefined : json['updatedUser'],
    };
}

export function MmsNovelToJSON(json: any): MmsNovel {
    return MmsNovelToJSONTyped(json, false);
}

export function MmsNovelToJSONTyped(value?: MmsNovel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'novelTitle': value['novelTitle'],
        'novelAuthor': value['novelAuthor'],
        'status': value['status'],
        'createTime': value['createTime'],
        'updateTime': value['updateTime'],
        'createdUser': value['createdUser'],
        'updatedUser': value['updatedUser'],
    };
}

