/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OmsJob
 */
export interface OmsJob {
    /**
     * 业务任务ID
     * @type {string}
     * @memberof OmsJob
     */
    jobId?: string;
    /**
     * 任务类型，如 file_batch
     * @type {string}
     * @memberof OmsJob
     */
    taskType?: string;
    /**
     * 0=queued,1=running,2=success,3=failed,4=canceled
     * @type {number}
     * @memberof OmsJob
     */
    status?: number;
    /**
     * 状态说明/失败摘要
     * @type {string}
     * @memberof OmsJob
     */
    message?: string;
    /**
     * 触发人
     * @type {string}
     * @memberof OmsJob
     */
    createdUser?: string;
    /**
     * 任务开始时间
     * @type {string}
     * @memberof OmsJob
     */
    startedTime?: string;
    /**
     * 任务结束时间
     * @type {string}
     * @memberof OmsJob
     */
    finishedTime?: string;
    /**
     * 创建时间
     * @type {string}
     * @memberof OmsJob
     */
    createTime?: string;
    /**
     * 修改时间
     * @type {string}
     * @memberof OmsJob
     */
    updateTime?: string;
}

/**
 * Check if a given object implements the OmsJob interface.
 */
export function instanceOfOmsJob(value: object): value is OmsJob {
    return true;
}

export function OmsJobFromJSON(json: any): OmsJob {
    return OmsJobFromJSONTyped(json, false);
}

export function OmsJobFromJSONTyped(json: any, ignoreDiscriminator: boolean): OmsJob {
    if (json == null) {
        return json;
    }
    return {
        
        'jobId': json['jobId'] == null ? undefined : json['jobId'],
        'taskType': json['taskType'] == null ? undefined : json['taskType'],
        'status': json['status'] == null ? undefined : json['status'],
        'message': json['message'] == null ? undefined : json['message'],
        'createdUser': json['createdUser'] == null ? undefined : json['createdUser'],
        'startedTime': json['startedTime'] == null ? undefined : json['startedTime'],
        'finishedTime': json['finishedTime'] == null ? undefined : json['finishedTime'],
        'createTime': json['createTime'] == null ? undefined : json['createTime'],
        'updateTime': json['updateTime'] == null ? undefined : json['updateTime'],
    };
}

export function OmsJobToJSON(json: any): OmsJob {
    return OmsJobToJSONTyped(json, false);
}

export function OmsJobToJSONTyped(value?: OmsJob | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jobId': value['jobId'],
        'taskType': value['taskType'],
        'status': value['status'],
        'message': value['message'],
        'createdUser': value['createdUser'],
        'startedTime': value['startedTime'],
        'finishedTime': value['finishedTime'],
        'createTime': value['createTime'],
        'updateTime': value['updateTime'],
    };
}

