/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OmsParameter
 */
export interface OmsParameter {
    /**
     * 主键
     * @type {number}
     * @memberof OmsParameter
     */
    paramCode?: number;
    /**
     * 参数名称
     * @type {string}
     * @memberof OmsParameter
     */
    paramName?: string;
    /**
     * 参数类型
     * @type {string}
     * @memberof OmsParameter
     */
    kindCode?: string;
    /**
     * 参数值
     * @type {string}
     * @memberof OmsParameter
     */
    paramValue?: string;
    /**
     * 参数描述
     * @type {string}
     * @memberof OmsParameter
     */
    paramDesc?: string;
    /**
     * 是否启用
     * @type {number}
     * @memberof OmsParameter
     */
    enabledFlag?: number;
    /**
     * 创建时间
     * @type {string}
     * @memberof OmsParameter
     */
    createTime?: string;
    /**
     * 修改时间
     * @type {string}
     * @memberof OmsParameter
     */
    updateTime?: string;
}

/**
 * Check if a given object implements the OmsParameter interface.
 */
export function instanceOfOmsParameter(value: object): value is OmsParameter {
    return true;
}

export function OmsParameterFromJSON(json: any): OmsParameter {
    return OmsParameterFromJSONTyped(json, false);
}

export function OmsParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): OmsParameter {
    if (json == null) {
        return json;
    }
    return {
        
        'paramCode': json['paramCode'] == null ? undefined : json['paramCode'],
        'paramName': json['paramName'] == null ? undefined : json['paramName'],
        'kindCode': json['kindCode'] == null ? undefined : json['kindCode'],
        'paramValue': json['paramValue'] == null ? undefined : json['paramValue'],
        'paramDesc': json['paramDesc'] == null ? undefined : json['paramDesc'],
        'enabledFlag': json['enabledFlag'] == null ? undefined : json['enabledFlag'],
        'createTime': json['createTime'] == null ? undefined : json['createTime'],
        'updateTime': json['updateTime'] == null ? undefined : json['updateTime'],
    };
}

export function OmsParameterToJSON(json: any): OmsParameter {
    return OmsParameterToJSONTyped(json, false);
}

export function OmsParameterToJSONTyped(value?: OmsParameter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'paramCode': value['paramCode'],
        'paramName': value['paramName'],
        'kindCode': value['kindCode'],
        'paramValue': value['paramValue'],
        'paramDesc': value['paramDesc'],
        'enabledFlag': value['enabledFlag'],
        'createTime': value['createTime'],
        'updateTime': value['updateTime'],
    };
}

