/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ParameterAddInput
 */
export interface ParameterAddInput {
    /**
     * 主键
     * @type {number}
     * @memberof ParameterAddInput
     */
    paramCode?: number;
    /**
     * 参数名称
     * @type {string}
     * @memberof ParameterAddInput
     */
    paramName?: string;
    /**
     * 参数类型
     * @type {string}
     * @memberof ParameterAddInput
     */
    kindCode?: string;
    /**
     * 参数值
     * @type {string}
     * @memberof ParameterAddInput
     */
    paramValue?: string;
    /**
     * 参数描述
     * @type {string}
     * @memberof ParameterAddInput
     */
    paramDesc?: string;
    /**
     * 是否启用
     * @type {number}
     * @memberof ParameterAddInput
     */
    enabledFlag?: number;
}

/**
 * Check if a given object implements the ParameterAddInput interface.
 */
export function instanceOfParameterAddInput(value: object): value is ParameterAddInput {
    return true;
}

export function ParameterAddInputFromJSON(json: any): ParameterAddInput {
    return ParameterAddInputFromJSONTyped(json, false);
}

export function ParameterAddInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ParameterAddInput {
    if (json == null) {
        return json;
    }
    return {
        
        'paramCode': json['paramCode'] == null ? undefined : json['paramCode'],
        'paramName': json['paramName'] == null ? undefined : json['paramName'],
        'kindCode': json['kindCode'] == null ? undefined : json['kindCode'],
        'paramValue': json['paramValue'] == null ? undefined : json['paramValue'],
        'paramDesc': json['paramDesc'] == null ? undefined : json['paramDesc'],
        'enabledFlag': json['enabledFlag'] == null ? undefined : json['enabledFlag'],
    };
}

export function ParameterAddInputToJSON(json: any): ParameterAddInput {
    return ParameterAddInputToJSONTyped(json, false);
}

export function ParameterAddInputToJSONTyped(value?: ParameterAddInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'paramCode': value['paramCode'],
        'paramName': value['paramName'],
        'kindCode': value['kindCode'],
        'paramValue': value['paramValue'],
        'paramDesc': value['paramDesc'],
        'enabledFlag': value['enabledFlag'],
    };
}

