/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserInfoVo } from './UserInfoVo';
import {
    UserInfoVoFromJSON,
    UserInfoVoFromJSONTyped,
    UserInfoVoToJSON,
    UserInfoVoToJSONTyped,
} from './UserInfoVo';

/**
 * 
 * @export
 * @interface ResultUserInfoVo
 */
export interface ResultUserInfoVo {
    /**
     * 
     * @type {number}
     * @memberof ResultUserInfoVo
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResultUserInfoVo
     */
    msg?: string;
    /**
     * 
     * @type {UserInfoVo}
     * @memberof ResultUserInfoVo
     */
    data?: UserInfoVo;
}

/**
 * Check if a given object implements the ResultUserInfoVo interface.
 */
export function instanceOfResultUserInfoVo(value: object): value is ResultUserInfoVo {
    return true;
}

export function ResultUserInfoVoFromJSON(json: any): ResultUserInfoVo {
    return ResultUserInfoVoFromJSONTyped(json, false);
}

export function ResultUserInfoVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultUserInfoVo {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : UserInfoVoFromJSON(json['data']),
    };
}

export function ResultUserInfoVoToJSON(json: any): ResultUserInfoVo {
    return ResultUserInfoVoToJSONTyped(json, false);
}

export function ResultUserInfoVoToJSONTyped(value?: ResultUserInfoVo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': UserInfoVoToJSON(value['data']),
    };
}

