/* tslint:disable */
/* eslint-disable */
/**
 * 个人项目
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseQueryPageOmsParameter } from './BaseQueryPageOmsParameter';
import {
    BaseQueryPageOmsParameterFromJSON,
    BaseQueryPageOmsParameterFromJSONTyped,
    BaseQueryPageOmsParameterToJSON,
    BaseQueryPageOmsParameterToJSONTyped,
} from './BaseQueryPageOmsParameter';

/**
 * 
 * @export
 * @interface ResultBaseQueryPageOmsParameter
 */
export interface ResultBaseQueryPageOmsParameter {
    /**
     * 
     * @type {number}
     * @memberof ResultBaseQueryPageOmsParameter
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResultBaseQueryPageOmsParameter
     */
    msg?: string;
    /**
     * 
     * @type {BaseQueryPageOmsParameter}
     * @memberof ResultBaseQueryPageOmsParameter
     */
    data?: BaseQueryPageOmsParameter;
}

/**
 * Check if a given object implements the ResultBaseQueryPageOmsParameter interface.
 */
export function instanceOfResultBaseQueryPageOmsParameter(value: object): value is ResultBaseQueryPageOmsParameter {
    return true;
}

export function ResultBaseQueryPageOmsParameterFromJSON(json: any): ResultBaseQueryPageOmsParameter {
    return ResultBaseQueryPageOmsParameterFromJSONTyped(json, false);
}

export function ResultBaseQueryPageOmsParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultBaseQueryPageOmsParameter {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : BaseQueryPageOmsParameterFromJSON(json['data']),
    };
}

export function ResultBaseQueryPageOmsParameterToJSON(json: any): ResultBaseQueryPageOmsParameter {
    return ResultBaseQueryPageOmsParameterToJSONTyped(json, false);
}

export function ResultBaseQueryPageOmsParameterToJSONTyped(value?: ResultBaseQueryPageOmsParameter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': BaseQueryPageOmsParameterToJSON(value['data']),
    };
}

