/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobDetailOutput } from './JobDetailOutput';
import {
    JobDetailOutputFromJSON,
    JobDetailOutputFromJSONTyped,
    JobDetailOutputToJSON,
    JobDetailOutputToJSONTyped,
} from './JobDetailOutput';

/**
 * 
 * @export
 * @interface ResultJobDetailOutput
 */
export interface ResultJobDetailOutput {
    /**
     * 
     * @type {number}
     * @memberof ResultJobDetailOutput
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResultJobDetailOutput
     */
    msg?: string;
    /**
     * 
     * @type {JobDetailOutput}
     * @memberof ResultJobDetailOutput
     */
    data?: JobDetailOutput;
}

/**
 * Check if a given object implements the ResultJobDetailOutput interface.
 */
export function instanceOfResultJobDetailOutput(value: object): value is ResultJobDetailOutput {
    return true;
}

export function ResultJobDetailOutputFromJSON(json: any): ResultJobDetailOutput {
    return ResultJobDetailOutputFromJSONTyped(json, false);
}

export function ResultJobDetailOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultJobDetailOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : JobDetailOutputFromJSON(json['data']),
    };
}

export function ResultJobDetailOutputToJSON(json: any): ResultJobDetailOutput {
    return ResultJobDetailOutputToJSONTyped(json, false);
}

export function ResultJobDetailOutputToJSONTyped(value?: ResultJobDetailOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': JobDetailOutputToJSON(value['data']),
    };
}

