/* tslint:disable */
/* eslint-disable */
/**
 * 个人项目
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QueryPageOmsParameter } from './QueryPageOmsParameter';
import {
    QueryPageOmsParameterFromJSON,
    QueryPageOmsParameterFromJSONTyped,
    QueryPageOmsParameterToJSON,
    QueryPageOmsParameterToJSONTyped,
} from './QueryPageOmsParameter';

/**
 * 
 * @export
 * @interface ResultQueryPageOmsParameter
 */
export interface ResultQueryPageOmsParameter {
    /**
     * 
     * @type {number}
     * @memberof ResultQueryPageOmsParameter
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResultQueryPageOmsParameter
     */
    msg?: string;
    /**
     * 
     * @type {QueryPageOmsParameter}
     * @memberof ResultQueryPageOmsParameter
     */
    data?: QueryPageOmsParameter;
}

/**
 * Check if a given object implements the ResultQueryPageOmsParameter interface.
 */
export function instanceOfResultQueryPageOmsParameter(value: object): value is ResultQueryPageOmsParameter {
    return true;
}

export function ResultQueryPageOmsParameterFromJSON(json: any): ResultQueryPageOmsParameter {
    return ResultQueryPageOmsParameterFromJSONTyped(json, false);
}

export function ResultQueryPageOmsParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultQueryPageOmsParameter {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : QueryPageOmsParameterFromJSON(json['data']),
    };
}

export function ResultQueryPageOmsParameterToJSON(json: any): ResultQueryPageOmsParameter {
    return ResultQueryPageOmsParameterToJSONTyped(json, false);
}

export function ResultQueryPageOmsParameterToJSONTyped(value?: ResultQueryPageOmsParameter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': QueryPageOmsParameterToJSON(value['data']),
    };
}

