/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskDetailOutput } from './TaskDetailOutput';
import {
    TaskDetailOutputFromJSON,
    TaskDetailOutputFromJSONTyped,
    TaskDetailOutputToJSON,
    TaskDetailOutputToJSONTyped,
} from './TaskDetailOutput';

/**
 * 
 * @export
 * @interface ResultTaskDetailOutput
 */
export interface ResultTaskDetailOutput {
    /**
     * 
     * @type {number}
     * @memberof ResultTaskDetailOutput
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResultTaskDetailOutput
     */
    msg?: string;
    /**
     * 
     * @type {TaskDetailOutput}
     * @memberof ResultTaskDetailOutput
     */
    data?: TaskDetailOutput;
}

/**
 * Check if a given object implements the ResultTaskDetailOutput interface.
 */
export function instanceOfResultTaskDetailOutput(value: object): value is ResultTaskDetailOutput {
    return true;
}

export function ResultTaskDetailOutputFromJSON(json: any): ResultTaskDetailOutput {
    return ResultTaskDetailOutputFromJSONTyped(json, false);
}

export function ResultTaskDetailOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultTaskDetailOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : TaskDetailOutputFromJSON(json['data']),
    };
}

export function ResultTaskDetailOutputToJSON(json: any): ResultTaskDetailOutput {
    return ResultTaskDetailOutputToJSONTyped(json, false);
}

export function ResultTaskDetailOutputToJSONTyped(value?: ResultTaskDetailOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': TaskDetailOutputToJSON(value['data']),
    };
}

