/* tslint:disable */
/* eslint-disable */
/**
 * 个人项目
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QueryPageMmsNovel } from './QueryPageMmsNovel';
import {
    QueryPageMmsNovelFromJSON,
    QueryPageMmsNovelFromJSONTyped,
    QueryPageMmsNovelToJSON,
    QueryPageMmsNovelToJSONTyped,
} from './QueryPageMmsNovel';

/**
 * 
 * @export
 * @interface ResultQueryPageMmsNovel
 */
export interface ResultQueryPageMmsNovel {
    /**
     * 
     * @type {number}
     * @memberof ResultQueryPageMmsNovel
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResultQueryPageMmsNovel
     */
    msg?: string;
    /**
     * 
     * @type {QueryPageMmsNovel}
     * @memberof ResultQueryPageMmsNovel
     */
    data?: QueryPageMmsNovel;
}

/**
 * Check if a given object implements the ResultQueryPageMmsNovel interface.
 */
export function instanceOfResultQueryPageMmsNovel(value: object): value is ResultQueryPageMmsNovel {
    return true;
}

export function ResultQueryPageMmsNovelFromJSON(json: any): ResultQueryPageMmsNovel {
    return ResultQueryPageMmsNovelFromJSONTyped(json, false);
}

export function ResultQueryPageMmsNovelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultQueryPageMmsNovel {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : QueryPageMmsNovelFromJSON(json['data']),
    };
}

export function ResultQueryPageMmsNovelToJSON(json: any): ResultQueryPageMmsNovel {
    return ResultQueryPageMmsNovelToJSONTyped(json, false);
}

export function ResultQueryPageMmsNovelToJSONTyped(value?: ResultQueryPageMmsNovel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': QueryPageMmsNovelToJSON(value['data']),
    };
}

