/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OmsUser } from './OmsUser';
import {
    OmsUserFromJSON,
    OmsUserFromJSONTyped,
    OmsUserToJSON,
    OmsUserToJSONTyped,
} from './OmsUser';

/**
 * 
 * @export
 * @interface ResultOmsUser
 */
export interface ResultOmsUser {
    /**
     * 
     * @type {number}
     * @memberof ResultOmsUser
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResultOmsUser
     */
    msg?: string;
    /**
     * 
     * @type {OmsUser}
     * @memberof ResultOmsUser
     */
    data?: OmsUser;
}

/**
 * Check if a given object implements the ResultOmsUser interface.
 */
export function instanceOfResultOmsUser(value: object): value is ResultOmsUser {
    return true;
}

export function ResultOmsUserFromJSON(json: any): ResultOmsUser {
    return ResultOmsUserFromJSONTyped(json, false);
}

export function ResultOmsUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultOmsUser {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : OmsUserFromJSON(json['data']),
    };
}

export function ResultOmsUserToJSON(json: any): ResultOmsUser {
    return ResultOmsUserToJSONTyped(json, false);
}

export function ResultOmsUserToJSONTyped(value?: ResultOmsUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': OmsUserToJSON(value['data']),
    };
}

