/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseQueryPageUserInfoVo } from './BaseQueryPageUserInfoVo';
import {
    BaseQueryPageUserInfoVoFromJSON,
    BaseQueryPageUserInfoVoFromJSONTyped,
    BaseQueryPageUserInfoVoToJSON,
    BaseQueryPageUserInfoVoToJSONTyped,
} from './BaseQueryPageUserInfoVo';

/**
 * 
 * @export
 * @interface ResultBaseQueryPageUserInfoVo
 */
export interface ResultBaseQueryPageUserInfoVo {
    /**
     * 
     * @type {number}
     * @memberof ResultBaseQueryPageUserInfoVo
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResultBaseQueryPageUserInfoVo
     */
    msg?: string;
    /**
     * 
     * @type {BaseQueryPageUserInfoVo}
     * @memberof ResultBaseQueryPageUserInfoVo
     */
    data?: BaseQueryPageUserInfoVo;
}

/**
 * Check if a given object implements the ResultBaseQueryPageUserInfoVo interface.
 */
export function instanceOfResultBaseQueryPageUserInfoVo(value: object): value is ResultBaseQueryPageUserInfoVo {
    return true;
}

export function ResultBaseQueryPageUserInfoVoFromJSON(json: any): ResultBaseQueryPageUserInfoVo {
    return ResultBaseQueryPageUserInfoVoFromJSONTyped(json, false);
}

export function ResultBaseQueryPageUserInfoVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultBaseQueryPageUserInfoVo {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : BaseQueryPageUserInfoVoFromJSON(json['data']),
    };
}

export function ResultBaseQueryPageUserInfoVoToJSON(json: any): ResultBaseQueryPageUserInfoVo {
    return ResultBaseQueryPageUserInfoVoToJSONTyped(json, false);
}

export function ResultBaseQueryPageUserInfoVoToJSONTyped(value?: ResultBaseQueryPageUserInfoVo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': BaseQueryPageUserInfoVoToJSON(value['data']),
    };
}

