/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseQueryPageMmsMeta } from './BaseQueryPageMmsMeta';
import {
    BaseQueryPageMmsMetaFromJSON,
    BaseQueryPageMmsMetaFromJSONTyped,
    BaseQueryPageMmsMetaToJSON,
    BaseQueryPageMmsMetaToJSONTyped,
} from './BaseQueryPageMmsMeta';

/**
 * 
 * @export
 * @interface ResultBaseQueryPageMmsMeta
 */
export interface ResultBaseQueryPageMmsMeta {
    /**
     * 
     * @type {number}
     * @memberof ResultBaseQueryPageMmsMeta
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResultBaseQueryPageMmsMeta
     */
    msg?: string;
    /**
     * 
     * @type {BaseQueryPageMmsMeta}
     * @memberof ResultBaseQueryPageMmsMeta
     */
    data?: BaseQueryPageMmsMeta;
}

/**
 * Check if a given object implements the ResultBaseQueryPageMmsMeta interface.
 */
export function instanceOfResultBaseQueryPageMmsMeta(value: object): value is ResultBaseQueryPageMmsMeta {
    return true;
}

export function ResultBaseQueryPageMmsMetaFromJSON(json: any): ResultBaseQueryPageMmsMeta {
    return ResultBaseQueryPageMmsMetaFromJSONTyped(json, false);
}

export function ResultBaseQueryPageMmsMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultBaseQueryPageMmsMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : BaseQueryPageMmsMetaFromJSON(json['data']),
    };
}

export function ResultBaseQueryPageMmsMetaToJSON(json: any): ResultBaseQueryPageMmsMeta {
    return ResultBaseQueryPageMmsMetaToJSONTyped(json, false);
}

export function ResultBaseQueryPageMmsMetaToJSONTyped(value?: ResultBaseQueryPageMmsMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': BaseQueryPageMmsMetaToJSON(value['data']),
    };
}

