/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseQueryPageWbTask } from './BaseQueryPageWbTask';
import {
    BaseQueryPageWbTaskFromJSON,
    BaseQueryPageWbTaskFromJSONTyped,
    BaseQueryPageWbTaskToJSON,
    BaseQueryPageWbTaskToJSONTyped,
} from './BaseQueryPageWbTask';

/**
 * 
 * @export
 * @interface ResultBaseQueryPageWbTask
 */
export interface ResultBaseQueryPageWbTask {
    /**
     * 
     * @type {number}
     * @memberof ResultBaseQueryPageWbTask
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResultBaseQueryPageWbTask
     */
    msg?: string;
    /**
     * 
     * @type {BaseQueryPageWbTask}
     * @memberof ResultBaseQueryPageWbTask
     */
    data?: BaseQueryPageWbTask;
}

/**
 * Check if a given object implements the ResultBaseQueryPageWbTask interface.
 */
export function instanceOfResultBaseQueryPageWbTask(value: object): value is ResultBaseQueryPageWbTask {
    return true;
}

export function ResultBaseQueryPageWbTaskFromJSON(json: any): ResultBaseQueryPageWbTask {
    return ResultBaseQueryPageWbTaskFromJSONTyped(json, false);
}

export function ResultBaseQueryPageWbTaskFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultBaseQueryPageWbTask {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : BaseQueryPageWbTaskFromJSON(json['data']),
    };
}

export function ResultBaseQueryPageWbTaskToJSON(json: any): ResultBaseQueryPageWbTask {
    return ResultBaseQueryPageWbTaskToJSONTyped(json, false);
}

export function ResultBaseQueryPageWbTaskToJSONTyped(value?: ResultBaseQueryPageWbTask | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': BaseQueryPageWbTaskToJSON(value['data']),
    };
}

