/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResultBoolean
 */
export interface ResultBoolean {
    /**
     * 
     * @type {number}
     * @memberof ResultBoolean
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResultBoolean
     */
    msg?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ResultBoolean
     */
    data?: boolean;
}

/**
 * Check if a given object implements the ResultBoolean interface.
 */
export function instanceOfResultBoolean(value: object): value is ResultBoolean {
    return true;
}

export function ResultBooleanFromJSON(json: any): ResultBoolean {
    return ResultBooleanFromJSONTyped(json, false);
}

export function ResultBooleanFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultBoolean {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function ResultBooleanToJSON(json: any): ResultBoolean {
    return ResultBooleanToJSONTyped(json, false);
}

export function ResultBooleanToJSONTyped(value?: ResultBoolean | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': value['data'],
    };
}

