/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseQueryPageLocalFileSimpleDto } from './BaseQueryPageLocalFileSimpleDto';
import {
    BaseQueryPageLocalFileSimpleDtoFromJSON,
    BaseQueryPageLocalFileSimpleDtoFromJSONTyped,
    BaseQueryPageLocalFileSimpleDtoToJSON,
    BaseQueryPageLocalFileSimpleDtoToJSONTyped,
} from './BaseQueryPageLocalFileSimpleDto';

/**
 * 
 * @export
 * @interface ResultBaseQueryPageLocalFileSimpleDto
 */
export interface ResultBaseQueryPageLocalFileSimpleDto {
    /**
     * 
     * @type {number}
     * @memberof ResultBaseQueryPageLocalFileSimpleDto
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResultBaseQueryPageLocalFileSimpleDto
     */
    msg?: string;
    /**
     * 
     * @type {BaseQueryPageLocalFileSimpleDto}
     * @memberof ResultBaseQueryPageLocalFileSimpleDto
     */
    data?: BaseQueryPageLocalFileSimpleDto;
}

/**
 * Check if a given object implements the ResultBaseQueryPageLocalFileSimpleDto interface.
 */
export function instanceOfResultBaseQueryPageLocalFileSimpleDto(value: object): value is ResultBaseQueryPageLocalFileSimpleDto {
    return true;
}

export function ResultBaseQueryPageLocalFileSimpleDtoFromJSON(json: any): ResultBaseQueryPageLocalFileSimpleDto {
    return ResultBaseQueryPageLocalFileSimpleDtoFromJSONTyped(json, false);
}

export function ResultBaseQueryPageLocalFileSimpleDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultBaseQueryPageLocalFileSimpleDto {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : BaseQueryPageLocalFileSimpleDtoFromJSON(json['data']),
    };
}

export function ResultBaseQueryPageLocalFileSimpleDtoToJSON(json: any): ResultBaseQueryPageLocalFileSimpleDto {
    return ResultBaseQueryPageLocalFileSimpleDtoToJSONTyped(json, false);
}

export function ResultBaseQueryPageLocalFileSimpleDtoToJSONTyped(value?: ResultBaseQueryPageLocalFileSimpleDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': BaseQueryPageLocalFileSimpleDtoToJSON(value['data']),
    };
}

