/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WbTask } from './WbTask';
import {
    WbTaskFromJSON,
    WbTaskFromJSONTyped,
    WbTaskToJSON,
    WbTaskToJSONTyped,
} from './WbTask';

/**
 * 
 * @export
 * @interface ResultWbTask
 */
export interface ResultWbTask {
    /**
     * 
     * @type {number}
     * @memberof ResultWbTask
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResultWbTask
     */
    msg?: string;
    /**
     * 
     * @type {WbTask}
     * @memberof ResultWbTask
     */
    data?: WbTask;
}

/**
 * Check if a given object implements the ResultWbTask interface.
 */
export function instanceOfResultWbTask(value: object): value is ResultWbTask {
    return true;
}

export function ResultWbTaskFromJSON(json: any): ResultWbTask {
    return ResultWbTaskFromJSONTyped(json, false);
}

export function ResultWbTaskFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultWbTask {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : WbTaskFromJSON(json['data']),
    };
}

export function ResultWbTaskToJSON(json: any): ResultWbTask {
    return ResultWbTaskToJSONTyped(json, false);
}

export function ResultWbTaskToJSONTyped(value?: ResultWbTask | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': WbTaskToJSON(value['data']),
    };
}

