/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WbTask } from './WbTask';
import {
    WbTaskFromJSON,
    WbTaskFromJSONTyped,
    WbTaskToJSON,
    WbTaskToJSONTyped,
} from './WbTask';

/**
 * 
 * @export
 * @interface ResultListWbTask
 */
export interface ResultListWbTask {
    /**
     * 
     * @type {number}
     * @memberof ResultListWbTask
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResultListWbTask
     */
    msg?: string;
    /**
     * 
     * @type {Array<WbTask>}
     * @memberof ResultListWbTask
     */
    data?: Array<WbTask>;
}

/**
 * Check if a given object implements the ResultListWbTask interface.
 */
export function instanceOfResultListWbTask(value: object): value is ResultListWbTask {
    return true;
}

export function ResultListWbTaskFromJSON(json: any): ResultListWbTask {
    return ResultListWbTaskFromJSONTyped(json, false);
}

export function ResultListWbTaskFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultListWbTask {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(WbTaskFromJSON)),
    };
}

export function ResultListWbTaskToJSON(json: any): ResultListWbTask {
    return ResultListWbTaskToJSONTyped(json, false);
}

export function ResultListWbTaskToJSONTyped(value?: ResultListWbTask | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(WbTaskToJSON)),
    };
}

