/* tslint:disable */
/* eslint-disable */
/**
 * 个人项目
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MmsNovelFile } from './MmsNovelFile';
import {
    MmsNovelFileFromJSON,
    MmsNovelFileFromJSONTyped,
    MmsNovelFileToJSON,
    MmsNovelFileToJSONTyped,
} from './MmsNovelFile';

/**
 * 
 * @export
 * @interface ResultListMmsNovelFile
 */
export interface ResultListMmsNovelFile {
    /**
     * 
     * @type {number}
     * @memberof ResultListMmsNovelFile
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResultListMmsNovelFile
     */
    msg?: string;
    /**
     * 
     * @type {Array<MmsNovelFile>}
     * @memberof ResultListMmsNovelFile
     */
    data?: Array<MmsNovelFile>;
}

/**
 * Check if a given object implements the ResultListMmsNovelFile interface.
 */
export function instanceOfResultListMmsNovelFile(value: object): value is ResultListMmsNovelFile {
    return true;
}

export function ResultListMmsNovelFileFromJSON(json: any): ResultListMmsNovelFile {
    return ResultListMmsNovelFileFromJSONTyped(json, false);
}

export function ResultListMmsNovelFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultListMmsNovelFile {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(MmsNovelFileFromJSON)),
    };
}

export function ResultListMmsNovelFileToJSON(json: any): ResultListMmsNovelFile {
    return ResultListMmsNovelFileToJSONTyped(json, false);
}

export function ResultListMmsNovelFileToJSONTyped(value?: ResultListMmsNovelFile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(MmsNovelFileToJSON)),
    };
}

