/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobMonitorOutput } from './JobMonitorOutput';
import {
    JobMonitorOutputFromJSON,
    JobMonitorOutputFromJSONTyped,
    JobMonitorOutputToJSON,
    JobMonitorOutputToJSONTyped,
} from './JobMonitorOutput';

/**
 * 
 * @export
 * @interface ResultJobMonitorOutput
 */
export interface ResultJobMonitorOutput {
    /**
     * 
     * @type {number}
     * @memberof ResultJobMonitorOutput
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResultJobMonitorOutput
     */
    msg?: string;
    /**
     * 
     * @type {JobMonitorOutput}
     * @memberof ResultJobMonitorOutput
     */
    data?: JobMonitorOutput;
}

/**
 * Check if a given object implements the ResultJobMonitorOutput interface.
 */
export function instanceOfResultJobMonitorOutput(value: object): value is ResultJobMonitorOutput {
    return true;
}

export function ResultJobMonitorOutputFromJSON(json: any): ResultJobMonitorOutput {
    return ResultJobMonitorOutputFromJSONTyped(json, false);
}

export function ResultJobMonitorOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultJobMonitorOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : JobMonitorOutputFromJSON(json['data']),
    };
}

export function ResultJobMonitorOutputToJSON(json: any): ResultJobMonitorOutput {
    return ResultJobMonitorOutputToJSONTyped(json, false);
}

export function ResultJobMonitorOutputToJSONTyped(value?: ResultJobMonitorOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': JobMonitorOutputToJSON(value['data']),
    };
}

