/* tslint:disable */
/* eslint-disable */
/**
 * 个人项目
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OmsJob } from './OmsJob';
import {
    OmsJobFromJSON,
    OmsJobFromJSONTyped,
    OmsJobToJSON,
    OmsJobToJSONTyped,
} from './OmsJob';

/**
 * 
 * @export
 * @interface ResultOmsJob
 */
export interface ResultOmsJob {
    /**
     * 
     * @type {number}
     * @memberof ResultOmsJob
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResultOmsJob
     */
    msg?: string;
    /**
     * 
     * @type {OmsJob}
     * @memberof ResultOmsJob
     */
    data?: OmsJob;
}

/**
 * Check if a given object implements the ResultOmsJob interface.
 */
export function instanceOfResultOmsJob(value: object): value is ResultOmsJob {
    return true;
}

export function ResultOmsJobFromJSON(json: any): ResultOmsJob {
    return ResultOmsJobFromJSONTyped(json, false);
}

export function ResultOmsJobFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultOmsJob {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : OmsJobFromJSON(json['data']),
    };
}

export function ResultOmsJobToJSON(json: any): ResultOmsJob {
    return ResultOmsJobToJSONTyped(json, false);
}

export function ResultOmsJobToJSONTyped(value?: ResultOmsJob | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': OmsJobToJSON(value['data']),
    };
}

