/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseQueryPageMmsNovel } from './BaseQueryPageMmsNovel';
import {
    BaseQueryPageMmsNovelFromJSON,
    BaseQueryPageMmsNovelFromJSONTyped,
    BaseQueryPageMmsNovelToJSON,
    BaseQueryPageMmsNovelToJSONTyped,
} from './BaseQueryPageMmsNovel';

/**
 * 
 * @export
 * @interface ResultBaseQueryPageMmsNovel
 */
export interface ResultBaseQueryPageMmsNovel {
    /**
     * 
     * @type {number}
     * @memberof ResultBaseQueryPageMmsNovel
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResultBaseQueryPageMmsNovel
     */
    msg?: string;
    /**
     * 
     * @type {BaseQueryPageMmsNovel}
     * @memberof ResultBaseQueryPageMmsNovel
     */
    data?: BaseQueryPageMmsNovel;
}

/**
 * Check if a given object implements the ResultBaseQueryPageMmsNovel interface.
 */
export function instanceOfResultBaseQueryPageMmsNovel(value: object): value is ResultBaseQueryPageMmsNovel {
    return true;
}

export function ResultBaseQueryPageMmsNovelFromJSON(json: any): ResultBaseQueryPageMmsNovel {
    return ResultBaseQueryPageMmsNovelFromJSONTyped(json, false);
}

export function ResultBaseQueryPageMmsNovelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultBaseQueryPageMmsNovel {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : BaseQueryPageMmsNovelFromJSON(json['data']),
    };
}

export function ResultBaseQueryPageMmsNovelToJSON(json: any): ResultBaseQueryPageMmsNovel {
    return ResultBaseQueryPageMmsNovelToJSONTyped(json, false);
}

export function ResultBaseQueryPageMmsNovelToJSONTyped(value?: ResultBaseQueryPageMmsNovel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': BaseQueryPageMmsNovelToJSON(value['data']),
    };
}

