/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseQueryPageMmsNovelFile } from './BaseQueryPageMmsNovelFile';
import {
    BaseQueryPageMmsNovelFileFromJSON,
    BaseQueryPageMmsNovelFileFromJSONTyped,
    BaseQueryPageMmsNovelFileToJSON,
    BaseQueryPageMmsNovelFileToJSONTyped,
} from './BaseQueryPageMmsNovelFile';

/**
 * 
 * @export
 * @interface ResultBaseQueryPageMmsNovelFile
 */
export interface ResultBaseQueryPageMmsNovelFile {
    /**
     * 
     * @type {number}
     * @memberof ResultBaseQueryPageMmsNovelFile
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResultBaseQueryPageMmsNovelFile
     */
    msg?: string;
    /**
     * 
     * @type {BaseQueryPageMmsNovelFile}
     * @memberof ResultBaseQueryPageMmsNovelFile
     */
    data?: BaseQueryPageMmsNovelFile;
}

/**
 * Check if a given object implements the ResultBaseQueryPageMmsNovelFile interface.
 */
export function instanceOfResultBaseQueryPageMmsNovelFile(value: object): value is ResultBaseQueryPageMmsNovelFile {
    return true;
}

export function ResultBaseQueryPageMmsNovelFileFromJSON(json: any): ResultBaseQueryPageMmsNovelFile {
    return ResultBaseQueryPageMmsNovelFileFromJSONTyped(json, false);
}

export function ResultBaseQueryPageMmsNovelFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultBaseQueryPageMmsNovelFile {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : BaseQueryPageMmsNovelFileFromJSON(json['data']),
    };
}

export function ResultBaseQueryPageMmsNovelFileToJSON(json: any): ResultBaseQueryPageMmsNovelFile {
    return ResultBaseQueryPageMmsNovelFileToJSONTyped(json, false);
}

export function ResultBaseQueryPageMmsNovelFileToJSONTyped(value?: ResultBaseQueryPageMmsNovelFile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': BaseQueryPageMmsNovelFileToJSON(value['data']),
    };
}

