/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseQueryPageOmsTask } from './BaseQueryPageOmsTask';
import {
    BaseQueryPageOmsTaskFromJSON,
    BaseQueryPageOmsTaskFromJSONTyped,
    BaseQueryPageOmsTaskToJSON,
    BaseQueryPageOmsTaskToJSONTyped,
} from './BaseQueryPageOmsTask';

/**
 * 
 * @export
 * @interface ResultBaseQueryPageOmsTask
 */
export interface ResultBaseQueryPageOmsTask {
    /**
     * 
     * @type {number}
     * @memberof ResultBaseQueryPageOmsTask
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResultBaseQueryPageOmsTask
     */
    msg?: string;
    /**
     * 
     * @type {BaseQueryPageOmsTask}
     * @memberof ResultBaseQueryPageOmsTask
     */
    data?: BaseQueryPageOmsTask;
}

/**
 * Check if a given object implements the ResultBaseQueryPageOmsTask interface.
 */
export function instanceOfResultBaseQueryPageOmsTask(value: object): value is ResultBaseQueryPageOmsTask {
    return true;
}

export function ResultBaseQueryPageOmsTaskFromJSON(json: any): ResultBaseQueryPageOmsTask {
    return ResultBaseQueryPageOmsTaskFromJSONTyped(json, false);
}

export function ResultBaseQueryPageOmsTaskFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultBaseQueryPageOmsTask {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : BaseQueryPageOmsTaskFromJSON(json['data']),
    };
}

export function ResultBaseQueryPageOmsTaskToJSON(json: any): ResultBaseQueryPageOmsTask {
    return ResultBaseQueryPageOmsTaskToJSONTyped(json, false);
}

export function ResultBaseQueryPageOmsTaskToJSONTyped(value?: ResultBaseQueryPageOmsTask | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': BaseQueryPageOmsTaskToJSON(value['data']),
    };
}

