/* tslint:disable */
/* eslint-disable */
/**
 * 个人项目
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QueryPageLocalFileSimpleDto } from './QueryPageLocalFileSimpleDto';
import {
    QueryPageLocalFileSimpleDtoFromJSON,
    QueryPageLocalFileSimpleDtoFromJSONTyped,
    QueryPageLocalFileSimpleDtoToJSON,
    QueryPageLocalFileSimpleDtoToJSONTyped,
} from './QueryPageLocalFileSimpleDto';

/**
 * 
 * @export
 * @interface ResultQueryPageLocalFileSimpleDto
 */
export interface ResultQueryPageLocalFileSimpleDto {
    /**
     * 
     * @type {number}
     * @memberof ResultQueryPageLocalFileSimpleDto
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResultQueryPageLocalFileSimpleDto
     */
    msg?: string;
    /**
     * 
     * @type {QueryPageLocalFileSimpleDto}
     * @memberof ResultQueryPageLocalFileSimpleDto
     */
    data?: QueryPageLocalFileSimpleDto;
}

/**
 * Check if a given object implements the ResultQueryPageLocalFileSimpleDto interface.
 */
export function instanceOfResultQueryPageLocalFileSimpleDto(value: object): value is ResultQueryPageLocalFileSimpleDto {
    return true;
}

export function ResultQueryPageLocalFileSimpleDtoFromJSON(json: any): ResultQueryPageLocalFileSimpleDto {
    return ResultQueryPageLocalFileSimpleDtoFromJSONTyped(json, false);
}

export function ResultQueryPageLocalFileSimpleDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultQueryPageLocalFileSimpleDto {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : QueryPageLocalFileSimpleDtoFromJSON(json['data']),
    };
}

export function ResultQueryPageLocalFileSimpleDtoToJSON(json: any): ResultQueryPageLocalFileSimpleDto {
    return ResultQueryPageLocalFileSimpleDtoToJSONTyped(json, false);
}

export function ResultQueryPageLocalFileSimpleDtoToJSONTyped(value?: ResultQueryPageLocalFileSimpleDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': QueryPageLocalFileSimpleDtoToJSON(value['data']),
    };
}

