/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OmsTask } from './OmsTask';
import {
    OmsTaskFromJSON,
    OmsTaskFromJSONTyped,
    OmsTaskToJSON,
    OmsTaskToJSONTyped,
} from './OmsTask';

/**
 * 
 * @export
 * @interface ResultOmsTask
 */
export interface ResultOmsTask {
    /**
     * 
     * @type {number}
     * @memberof ResultOmsTask
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResultOmsTask
     */
    msg?: string;
    /**
     * 
     * @type {OmsTask}
     * @memberof ResultOmsTask
     */
    data?: OmsTask;
}

/**
 * Check if a given object implements the ResultOmsTask interface.
 */
export function instanceOfResultOmsTask(value: object): value is ResultOmsTask {
    return true;
}

export function ResultOmsTaskFromJSON(json: any): ResultOmsTask {
    return ResultOmsTaskFromJSONTyped(json, false);
}

export function ResultOmsTaskFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultOmsTask {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : OmsTaskFromJSON(json['data']),
    };
}

export function ResultOmsTaskToJSON(json: any): ResultOmsTask {
    return ResultOmsTaskToJSONTyped(json, false);
}

export function ResultOmsTaskToJSONTyped(value?: ResultOmsTask | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': OmsTaskToJSON(value['data']),
    };
}

