/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MmsMeta } from './MmsMeta';
import {
    MmsMetaFromJSON,
    MmsMetaFromJSONTyped,
    MmsMetaToJSON,
    MmsMetaToJSONTyped,
} from './MmsMeta';

/**
 * 
 * @export
 * @interface ResultMmsMeta
 */
export interface ResultMmsMeta {
    /**
     * 
     * @type {number}
     * @memberof ResultMmsMeta
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResultMmsMeta
     */
    msg?: string;
    /**
     * 
     * @type {MmsMeta}
     * @memberof ResultMmsMeta
     */
    data?: MmsMeta;
}

/**
 * Check if a given object implements the ResultMmsMeta interface.
 */
export function instanceOfResultMmsMeta(value: object): value is ResultMmsMeta {
    return true;
}

export function ResultMmsMetaFromJSON(json: any): ResultMmsMeta {
    return ResultMmsMetaFromJSONTyped(json, false);
}

export function ResultMmsMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultMmsMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : MmsMetaFromJSON(json['data']),
    };
}

export function ResultMmsMetaToJSON(json: any): ResultMmsMeta {
    return ResultMmsMetaToJSONTyped(json, false);
}

export function ResultMmsMetaToJSONTyped(value?: ResultMmsMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': MmsMetaToJSON(value['data']),
    };
}

