/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskMonitorOutput } from './TaskMonitorOutput';
import {
    TaskMonitorOutputFromJSON,
    TaskMonitorOutputFromJSONTyped,
    TaskMonitorOutputToJSON,
    TaskMonitorOutputToJSONTyped,
} from './TaskMonitorOutput';

/**
 * 
 * @export
 * @interface ResultTaskMonitorOutput
 */
export interface ResultTaskMonitorOutput {
    /**
     * 
     * @type {number}
     * @memberof ResultTaskMonitorOutput
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResultTaskMonitorOutput
     */
    msg?: string;
    /**
     * 
     * @type {TaskMonitorOutput}
     * @memberof ResultTaskMonitorOutput
     */
    data?: TaskMonitorOutput;
}

/**
 * Check if a given object implements the ResultTaskMonitorOutput interface.
 */
export function instanceOfResultTaskMonitorOutput(value: object): value is ResultTaskMonitorOutput {
    return true;
}

export function ResultTaskMonitorOutputFromJSON(json: any): ResultTaskMonitorOutput {
    return ResultTaskMonitorOutputFromJSONTyped(json, false);
}

export function ResultTaskMonitorOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultTaskMonitorOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : TaskMonitorOutputFromJSON(json['data']),
    };
}

export function ResultTaskMonitorOutputToJSON(json: any): ResultTaskMonitorOutput {
    return ResultTaskMonitorOutputToJSONTyped(json, false);
}

export function ResultTaskMonitorOutputToJSONTyped(value?: ResultTaskMonitorOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': TaskMonitorOutputToJSON(value['data']),
    };
}

