/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResultString
 */
export interface ResultString {
    /**
     * 
     * @type {number}
     * @memberof ResultString
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResultString
     */
    msg?: string;
    /**
     * 
     * @type {string}
     * @memberof ResultString
     */
    data?: string;
}

/**
 * Check if a given object implements the ResultString interface.
 */
export function instanceOfResultString(value: object): value is ResultString {
    return true;
}

export function ResultStringFromJSON(json: any): ResultString {
    return ResultStringFromJSONTyped(json, false);
}

export function ResultStringFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultString {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function ResultStringToJSON(json: any): ResultString {
    return ResultStringToJSONTyped(json, false);
}

export function ResultStringToJSONTyped(value?: ResultString | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': value['data'],
    };
}

