/* tslint:disable */
/* eslint-disable */
/**
 * 个人项目
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseQueryPageOmsJob } from './BaseQueryPageOmsJob';
import {
    BaseQueryPageOmsJobFromJSON,
    BaseQueryPageOmsJobFromJSONTyped,
    BaseQueryPageOmsJobToJSON,
    BaseQueryPageOmsJobToJSONTyped,
} from './BaseQueryPageOmsJob';

/**
 * 
 * @export
 * @interface ResultBaseQueryPageOmsJob
 */
export interface ResultBaseQueryPageOmsJob {
    /**
     * 
     * @type {number}
     * @memberof ResultBaseQueryPageOmsJob
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResultBaseQueryPageOmsJob
     */
    msg?: string;
    /**
     * 
     * @type {BaseQueryPageOmsJob}
     * @memberof ResultBaseQueryPageOmsJob
     */
    data?: BaseQueryPageOmsJob;
}

/**
 * Check if a given object implements the ResultBaseQueryPageOmsJob interface.
 */
export function instanceOfResultBaseQueryPageOmsJob(value: object): value is ResultBaseQueryPageOmsJob {
    return true;
}

export function ResultBaseQueryPageOmsJobFromJSON(json: any): ResultBaseQueryPageOmsJob {
    return ResultBaseQueryPageOmsJobFromJSONTyped(json, false);
}

export function ResultBaseQueryPageOmsJobFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultBaseQueryPageOmsJob {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : BaseQueryPageOmsJobFromJSON(json['data']),
    };
}

export function ResultBaseQueryPageOmsJobToJSON(json: any): ResultBaseQueryPageOmsJob {
    return ResultBaseQueryPageOmsJobToJSONTyped(json, false);
}

export function ResultBaseQueryPageOmsJobToJSONTyped(value?: ResultBaseQueryPageOmsJob | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': BaseQueryPageOmsJobToJSON(value['data']),
    };
}

