/* tslint:disable */
/* eslint-disable */
/**
 * 个人项目
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QueryPageMmsNovelFile } from './QueryPageMmsNovelFile';
import {
    QueryPageMmsNovelFileFromJSON,
    QueryPageMmsNovelFileFromJSONTyped,
    QueryPageMmsNovelFileToJSON,
    QueryPageMmsNovelFileToJSONTyped,
} from './QueryPageMmsNovelFile';

/**
 * 
 * @export
 * @interface ResultQueryPageMmsNovelFile
 */
export interface ResultQueryPageMmsNovelFile {
    /**
     * 
     * @type {number}
     * @memberof ResultQueryPageMmsNovelFile
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResultQueryPageMmsNovelFile
     */
    msg?: string;
    /**
     * 
     * @type {QueryPageMmsNovelFile}
     * @memberof ResultQueryPageMmsNovelFile
     */
    data?: QueryPageMmsNovelFile;
}

/**
 * Check if a given object implements the ResultQueryPageMmsNovelFile interface.
 */
export function instanceOfResultQueryPageMmsNovelFile(value: object): value is ResultQueryPageMmsNovelFile {
    return true;
}

export function ResultQueryPageMmsNovelFileFromJSON(json: any): ResultQueryPageMmsNovelFile {
    return ResultQueryPageMmsNovelFileFromJSONTyped(json, false);
}

export function ResultQueryPageMmsNovelFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultQueryPageMmsNovelFile {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'data': json['data'] == null ? undefined : QueryPageMmsNovelFileFromJSON(json['data']),
    };
}

export function ResultQueryPageMmsNovelFileToJSON(json: any): ResultQueryPageMmsNovelFile {
    return ResultQueryPageMmsNovelFileToJSONTyped(json, false);
}

export function ResultQueryPageMmsNovelFileToJSONTyped(value?: ResultQueryPageMmsNovelFile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'data': QueryPageMmsNovelFileToJSON(value['data']),
    };
}

