/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskProgressDto
 */
export interface TaskProgressDto {
    /**
     * 
     * @type {number}
     * @memberof TaskProgressDto
     */
    current?: number;
    /**
     * 
     * @type {number}
     * @memberof TaskProgressDto
     */
    total?: number;
}

/**
 * Check if a given object implements the TaskProgressDto interface.
 */
export function instanceOfTaskProgressDto(value: object): value is TaskProgressDto {
    return true;
}

export function TaskProgressDtoFromJSON(json: any): TaskProgressDto {
    return TaskProgressDtoFromJSONTyped(json, false);
}

export function TaskProgressDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskProgressDto {
    if (json == null) {
        return json;
    }
    return {
        
        'current': json['current'] == null ? undefined : json['current'],
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function TaskProgressDtoToJSON(json: any): TaskProgressDto {
    return TaskProgressDtoToJSONTyped(json, false);
}

export function TaskProgressDtoToJSONTyped(value?: TaskProgressDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'current': value['current'],
        'total': value['total'],
    };
}

