/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskProgressDto } from './TaskProgressDto';
import {
    TaskProgressDtoFromJSON,
    TaskProgressDtoFromJSONTyped,
    TaskProgressDtoToJSON,
    TaskProgressDtoToJSONTyped,
} from './TaskProgressDto';

/**
 * 
 * @export
 * @interface TaskDetailOutput
 */
export interface TaskDetailOutput {
    /**
     * 业务任务ID
     * @type {string}
     * @memberof TaskDetailOutput
     */
    taskId?: string;
    /**
     * 任务标签, 用于分配到不同的处理器
     * @type {string}
     * @memberof TaskDetailOutput
     */
    taskTag?: string;
    /**
     * 该任务是否允许重试，0表示不允许重试，1表示允许重试
     * @type {number}
     * @memberof TaskDetailOutput
     */
    allowRetry?: number;
    /**
     * 业务标签
     * @type {string}
     * @memberof TaskDetailOutput
     */
    bizTag?: string;
    /**
     * 业务值
     * @type {string}
     * @memberof TaskDetailOutput
     */
    bizValue?: string;
    /**
     * 0=queued,1=running,2=success,3=failed,4=canceled
     * @type {number}
     * @memberof TaskDetailOutput
     */
    status?: number;
    /**
     * 状态说明/失败摘要
     * @type {string}
     * @memberof TaskDetailOutput
     */
    message?: string;
    /**
     * 任务对象(JSON格式), 重试时使用
     * @type {string}
     * @memberof TaskDetailOutput
     */
    taskObject?: string;
    /**
     * 触发人
     * @type {string}
     * @memberof TaskDetailOutput
     */
    createdUser?: string;
    /**
     * 任务开始时间
     * @type {string}
     * @memberof TaskDetailOutput
     */
    startedTime?: string;
    /**
     * 任务结束时间
     * @type {string}
     * @memberof TaskDetailOutput
     */
    finishedTime?: string;
    /**
     * 创建时间
     * @type {string}
     * @memberof TaskDetailOutput
     */
    createTime?: string;
    /**
     * 修改时间
     * @type {string}
     * @memberof TaskDetailOutput
     */
    updateTime?: string;
    /**
     * 
     * @type {TaskProgressDto}
     * @memberof TaskDetailOutput
     */
    taskProgressDTO?: TaskProgressDto;
    /**
     * 
     * @type {string}
     * @memberof TaskDetailOutput
     */
    taskLog?: string;
}

/**
 * Check if a given object implements the TaskDetailOutput interface.
 */
export function instanceOfTaskDetailOutput(value: object): value is TaskDetailOutput {
    return true;
}

export function TaskDetailOutputFromJSON(json: any): TaskDetailOutput {
    return TaskDetailOutputFromJSONTyped(json, false);
}

export function TaskDetailOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskDetailOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'taskId': json['taskId'] == null ? undefined : json['taskId'],
        'taskTag': json['taskTag'] == null ? undefined : json['taskTag'],
        'allowRetry': json['allowRetry'] == null ? undefined : json['allowRetry'],
        'bizTag': json['bizTag'] == null ? undefined : json['bizTag'],
        'bizValue': json['bizValue'] == null ? undefined : json['bizValue'],
        'status': json['status'] == null ? undefined : json['status'],
        'message': json['message'] == null ? undefined : json['message'],
        'taskObject': json['taskObject'] == null ? undefined : json['taskObject'],
        'createdUser': json['createdUser'] == null ? undefined : json['createdUser'],
        'startedTime': json['startedTime'] == null ? undefined : json['startedTime'],
        'finishedTime': json['finishedTime'] == null ? undefined : json['finishedTime'],
        'createTime': json['createTime'] == null ? undefined : json['createTime'],
        'updateTime': json['updateTime'] == null ? undefined : json['updateTime'],
        'taskProgressDTO': json['taskProgressDTO'] == null ? undefined : TaskProgressDtoFromJSON(json['taskProgressDTO']),
        'taskLog': json['taskLog'] == null ? undefined : json['taskLog'],
    };
}

export function TaskDetailOutputToJSON(json: any): TaskDetailOutput {
    return TaskDetailOutputToJSONTyped(json, false);
}

export function TaskDetailOutputToJSONTyped(value?: TaskDetailOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'taskId': value['taskId'],
        'taskTag': value['taskTag'],
        'allowRetry': value['allowRetry'],
        'bizTag': value['bizTag'],
        'bizValue': value['bizValue'],
        'status': value['status'],
        'message': value['message'],
        'taskObject': value['taskObject'],
        'createdUser': value['createdUser'],
        'startedTime': value['startedTime'],
        'finishedTime': value['finishedTime'],
        'createTime': value['createTime'],
        'updateTime': value['updateTime'],
        'taskProgressDTO': TaskProgressDtoToJSON(value['taskProgressDTO']),
        'taskLog': value['taskLog'],
    };
}

