/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ThreadPoolMetricsDto } from './ThreadPoolMetricsDto';
import {
    ThreadPoolMetricsDtoFromJSON,
    ThreadPoolMetricsDtoFromJSONTyped,
    ThreadPoolMetricsDtoToJSON,
    ThreadPoolMetricsDtoToJSONTyped,
} from './ThreadPoolMetricsDto';
import type { TaskOverviewDto } from './TaskOverviewDto';
import {
    TaskOverviewDtoFromJSON,
    TaskOverviewDtoFromJSONTyped,
    TaskOverviewDtoToJSON,
    TaskOverviewDtoToJSONTyped,
} from './TaskOverviewDto';

/**
 * 
 * @export
 * @interface TaskMonitorOutput
 */
export interface TaskMonitorOutput {
    /**
     * 
     * @type {ThreadPoolMetricsDto}
     * @memberof TaskMonitorOutput
     */
    threadPoolMetricsDTO?: ThreadPoolMetricsDto;
    /**
     * 
     * @type {TaskOverviewDto}
     * @memberof TaskMonitorOutput
     */
    taskOverviewDTO?: TaskOverviewDto;
}

/**
 * Check if a given object implements the TaskMonitorOutput interface.
 */
export function instanceOfTaskMonitorOutput(value: object): value is TaskMonitorOutput {
    return true;
}

export function TaskMonitorOutputFromJSON(json: any): TaskMonitorOutput {
    return TaskMonitorOutputFromJSONTyped(json, false);
}

export function TaskMonitorOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskMonitorOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'threadPoolMetricsDTO': json['threadPoolMetricsDTO'] == null ? undefined : ThreadPoolMetricsDtoFromJSON(json['threadPoolMetricsDTO']),
        'taskOverviewDTO': json['taskOverviewDTO'] == null ? undefined : TaskOverviewDtoFromJSON(json['taskOverviewDTO']),
    };
}

export function TaskMonitorOutputToJSON(json: any): TaskMonitorOutput {
    return TaskMonitorOutputToJSONTyped(json, false);
}

export function TaskMonitorOutputToJSONTyped(value?: TaskMonitorOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'threadPoolMetricsDTO': ThreadPoolMetricsDtoToJSON(value['threadPoolMetricsDTO']),
        'taskOverviewDTO': TaskOverviewDtoToJSON(value['taskOverviewDTO']),
    };
}

