/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskOverviewDto
 */
export interface TaskOverviewDto {
    /**
     * 
     * @type {number}
     * @memberof TaskOverviewDto
     */
    totalTaskCount?: number;
    /**
     * 
     * @type {number}
     * @memberof TaskOverviewDto
     */
    runningTaskCount?: number;
    /**
     * 
     * @type {number}
     * @memberof TaskOverviewDto
     */
    successTaskCount?: number;
    /**
     * 
     * @type {number}
     * @memberof TaskOverviewDto
     */
    failedTaskCount?: number;
}

/**
 * Check if a given object implements the TaskOverviewDto interface.
 */
export function instanceOfTaskOverviewDto(value: object): value is TaskOverviewDto {
    return true;
}

export function TaskOverviewDtoFromJSON(json: any): TaskOverviewDto {
    return TaskOverviewDtoFromJSONTyped(json, false);
}

export function TaskOverviewDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskOverviewDto {
    if (json == null) {
        return json;
    }
    return {
        
        'totalTaskCount': json['totalTaskCount'] == null ? undefined : json['totalTaskCount'],
        'runningTaskCount': json['runningTaskCount'] == null ? undefined : json['runningTaskCount'],
        'successTaskCount': json['successTaskCount'] == null ? undefined : json['successTaskCount'],
        'failedTaskCount': json['failedTaskCount'] == null ? undefined : json['failedTaskCount'],
    };
}

export function TaskOverviewDtoToJSON(json: any): TaskOverviewDto {
    return TaskOverviewDtoToJSONTyped(json, false);
}

export function TaskOverviewDtoToJSONTyped(value?: TaskOverviewDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalTaskCount': value['totalTaskCount'],
        'runningTaskCount': value['runningTaskCount'],
        'successTaskCount': value['successTaskCount'],
        'failedTaskCount': value['failedTaskCount'],
    };
}

