/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ThreadPoolMetricsDto
 */
export interface ThreadPoolMetricsDto {
    /**
     * 核心线程数
     * @type {number}
     * @memberof ThreadPoolMetricsDto
     */
    corePoolSize?: number;
    /**
     * 最大线程数
     * @type {number}
     * @memberof ThreadPoolMetricsDto
     */
    maxPoolSize?: number;
    /**
     * 活跃线程数
     * @type {number}
     * @memberof ThreadPoolMetricsDto
     */
    activeCount?: number;
    /**
     * 当前线程池大小
     * @type {number}
     * @memberof ThreadPoolMetricsDto
     */
    poolSize?: number;
    /**
     * 队列大小
     * @type {number}
     * @memberof ThreadPoolMetricsDto
     */
    queueSize?: number;
    /**
     * 已完成任务数
     * @type {number}
     * @memberof ThreadPoolMetricsDto
     */
    completedTaskCount?: number;
    /**
     * 历史最大线程数
     * @type {number}
     * @memberof ThreadPoolMetricsDto
     */
    largestPoolSize?: number;
    /**
     * 采集时间戳
     * @type {number}
     * @memberof ThreadPoolMetricsDto
     */
    timestamp?: number;
}

/**
 * Check if a given object implements the ThreadPoolMetricsDto interface.
 */
export function instanceOfThreadPoolMetricsDto(value: object): value is ThreadPoolMetricsDto {
    return true;
}

export function ThreadPoolMetricsDtoFromJSON(json: any): ThreadPoolMetricsDto {
    return ThreadPoolMetricsDtoFromJSONTyped(json, false);
}

export function ThreadPoolMetricsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThreadPoolMetricsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'corePoolSize': json['corePoolSize'] == null ? undefined : json['corePoolSize'],
        'maxPoolSize': json['maxPoolSize'] == null ? undefined : json['maxPoolSize'],
        'activeCount': json['activeCount'] == null ? undefined : json['activeCount'],
        'poolSize': json['poolSize'] == null ? undefined : json['poolSize'],
        'queueSize': json['queueSize'] == null ? undefined : json['queueSize'],
        'completedTaskCount': json['completedTaskCount'] == null ? undefined : json['completedTaskCount'],
        'largestPoolSize': json['largestPoolSize'] == null ? undefined : json['largestPoolSize'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
    };
}

export function ThreadPoolMetricsDtoToJSON(json: any): ThreadPoolMetricsDto {
    return ThreadPoolMetricsDtoToJSONTyped(json, false);
}

export function ThreadPoolMetricsDtoToJSONTyped(value?: ThreadPoolMetricsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'corePoolSize': value['corePoolSize'],
        'maxPoolSize': value['maxPoolSize'],
        'activeCount': value['activeCount'],
        'poolSize': value['poolSize'],
        'queueSize': value['queueSize'],
        'completedTaskCount': value['completedTaskCount'],
        'largestPoolSize': value['largestPoolSize'],
        'timestamp': value['timestamp'],
    };
}

