/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserInfoVo
 */
export interface UserInfoVo {
    /**
     * 用户ID
     * @type {string}
     * @memberof UserInfoVo
     */
    userId?: string;
    /**
     * 登录用户名
     * @type {string}
     * @memberof UserInfoVo
     */
    username?: string;
    /**
     * 用户昵称
     * @type {string}
     * @memberof UserInfoVo
     */
    nickname?: string;
    /**
     * 邮箱
     * @type {string}
     * @memberof UserInfoVo
     */
    email?: string;
    /**
     * 手机号
     * @type {string}
     * @memberof UserInfoVo
     */
    phone?: string;
    /**
     * 用户状态：0=禁用，1=正常，2=锁定
     * @type {number}
     * @memberof UserInfoVo
     */
    status?: number;
    /**
     * 最后登录IP
     * @type {string}
     * @memberof UserInfoVo
     */
    lastLoginIp?: string;
    /**
     * 最后登录时间
     * @type {string}
     * @memberof UserInfoVo
     */
    lastLoginTime?: string;
}

/**
 * Check if a given object implements the UserInfoVo interface.
 */
export function instanceOfUserInfoVo(value: object): value is UserInfoVo {
    return true;
}

export function UserInfoVoFromJSON(json: any): UserInfoVo {
    return UserInfoVoFromJSONTyped(json, false);
}

export function UserInfoVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserInfoVo {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'] == null ? undefined : json['userId'],
        'username': json['username'] == null ? undefined : json['username'],
        'nickname': json['nickname'] == null ? undefined : json['nickname'],
        'email': json['email'] == null ? undefined : json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'status': json['status'] == null ? undefined : json['status'],
        'lastLoginIp': json['lastLoginIp'] == null ? undefined : json['lastLoginIp'],
        'lastLoginTime': json['lastLoginTime'] == null ? undefined : json['lastLoginTime'],
    };
}

export function UserInfoVoToJSON(json: any): UserInfoVo {
    return UserInfoVoToJSONTyped(json, false);
}

export function UserInfoVoToJSONTyped(value?: UserInfoVo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'username': value['username'],
        'nickname': value['nickname'],
        'email': value['email'],
        'phone': value['phone'],
        'status': value['status'],
        'lastLoginIp': value['lastLoginIp'],
        'lastLoginTime': value['lastLoginTime'],
    };
}

