/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserUpdateInput
 */
export interface UserUpdateInput {
    /**
     * 用户ID
     * @type {string}
     * @memberof UserUpdateInput
     */
    userId?: string;
    /**
     * 登录用户名
     * @type {string}
     * @memberof UserUpdateInput
     */
    username?: string;
    /**
     * 登录密码(加密)
     * @type {string}
     * @memberof UserUpdateInput
     */
    password?: string;
    /**
     * 用户昵称
     * @type {string}
     * @memberof UserUpdateInput
     */
    nickname?: string;
    /**
     * 邮箱
     * @type {string}
     * @memberof UserUpdateInput
     */
    email?: string;
    /**
     * 手机号
     * @type {string}
     * @memberof UserUpdateInput
     */
    phone?: string;
    /**
     * 用户状态：0=禁用，1=正常，2=锁定
     * @type {number}
     * @memberof UserUpdateInput
     */
    status?: number;
}

/**
 * Check if a given object implements the UserUpdateInput interface.
 */
export function instanceOfUserUpdateInput(value: object): value is UserUpdateInput {
    return true;
}

export function UserUpdateInputFromJSON(json: any): UserUpdateInput {
    return UserUpdateInputFromJSONTyped(json, false);
}

export function UserUpdateInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserUpdateInput {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'] == null ? undefined : json['userId'],
        'username': json['username'] == null ? undefined : json['username'],
        'password': json['password'] == null ? undefined : json['password'],
        'nickname': json['nickname'] == null ? undefined : json['nickname'],
        'email': json['email'] == null ? undefined : json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function UserUpdateInputToJSON(json: any): UserUpdateInput {
    return UserUpdateInputToJSONTyped(json, false);
}

export function UserUpdateInputToJSONTyped(value?: UserUpdateInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'username': value['username'],
        'password': value['password'],
        'nickname': value['nickname'],
        'email': value['email'],
        'phone': value['phone'],
        'status': value['status'],
    };
}

