/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserCreateInput
 */
export interface UserCreateInput {
    /**
     * 登录用户名
     * @type {string}
     * @memberof UserCreateInput
     */
    username?: string;
    /**
     * 登录密码(加密)
     * @type {string}
     * @memberof UserCreateInput
     */
    password?: string;
    /**
     * 用户昵称
     * @type {string}
     * @memberof UserCreateInput
     */
    nickname?: string;
    /**
     * 邮箱
     * @type {string}
     * @memberof UserCreateInput
     */
    email?: string;
    /**
     * 手机号
     * @type {string}
     * @memberof UserCreateInput
     */
    phone?: string;
    /**
     * 用户状态：0=禁用，1=正常，2=锁定
     * @type {number}
     * @memberof UserCreateInput
     */
    status?: number;
}

/**
 * Check if a given object implements the UserCreateInput interface.
 */
export function instanceOfUserCreateInput(value: object): value is UserCreateInput {
    return true;
}

export function UserCreateInputFromJSON(json: any): UserCreateInput {
    return UserCreateInputFromJSONTyped(json, false);
}

export function UserCreateInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserCreateInput {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'] == null ? undefined : json['username'],
        'password': json['password'] == null ? undefined : json['password'],
        'nickname': json['nickname'] == null ? undefined : json['nickname'],
        'email': json['email'] == null ? undefined : json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function UserCreateInputToJSON(json: any): UserCreateInput {
    return UserCreateInputToJSONTyped(json, false);
}

export function UserCreateInputToJSONTyped(value?: UserCreateInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'password': value['password'],
        'nickname': value['nickname'],
        'email': value['email'],
        'phone': value['phone'],
        'status': value['status'],
    };
}

