/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WbTask
 */
export interface WbTask {
    /**
     * 任务ID
     * @type {string}
     * @memberof WbTask
     */
    id?: string;
    /**
     * 任务名称
     * @type {string}
     * @memberof WbTask
     */
    name?: string;
    /**
     * 任务描述
     * @type {string}
     * @memberof WbTask
     */
    description?: string;
    /**
     * 任务类型 0-普通 1-里程碑 2-子任务
     * @type {number}
     * @memberof WbTask
     */
    type?: number;
    /**
     * 任务分类
     * @type {string}
     * @memberof WbTask
     */
    tag?: string;
    /**
     * 任务状态 0-未开始 1-进行中 2-已完成 3-已取消
     * @type {number}
     * @memberof WbTask
     */
    status?: number;
    /**
     * 任务进度 0-100
     * @type {number}
     * @memberof WbTask
     */
    progress?: number;
    /**
     * 优先级 1-低 2-中 3-高 4-紧急
     * @type {number}
     * @memberof WbTask
     */
    priority?: number;
    /**
     * 父任务ID
     * @type {string}
     * @memberof WbTask
     */
    parentId?: string;
    /**
     * 任务开始时间
     * @type {string}
     * @memberof WbTask
     */
    startTime?: string;
    /**
     * 任务截止时间
     * @type {string}
     * @memberof WbTask
     */
    deadline?: string;
    /**
     * 任务完成时间
     * @type {string}
     * @memberof WbTask
     */
    completeTime?: string;
    /**
     * 创建时间
     * @type {string}
     * @memberof WbTask
     */
    createTime?: string;
    /**
     * 更新时间
     * @type {string}
     * @memberof WbTask
     */
    updateTime?: string;
}

/**
 * Check if a given object implements the WbTask interface.
 */
export function instanceOfWbTask(value: object): value is WbTask {
    return true;
}

export function WbTaskFromJSON(json: any): WbTask {
    return WbTaskFromJSONTyped(json, false);
}

export function WbTaskFromJSONTyped(json: any, ignoreDiscriminator: boolean): WbTask {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'type': json['type'] == null ? undefined : json['type'],
        'tag': json['tag'] == null ? undefined : json['tag'],
        'status': json['status'] == null ? undefined : json['status'],
        'progress': json['progress'] == null ? undefined : json['progress'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'parentId': json['parentId'] == null ? undefined : json['parentId'],
        'startTime': json['startTime'] == null ? undefined : json['startTime'],
        'deadline': json['deadline'] == null ? undefined : json['deadline'],
        'completeTime': json['completeTime'] == null ? undefined : json['completeTime'],
        'createTime': json['createTime'] == null ? undefined : json['createTime'],
        'updateTime': json['updateTime'] == null ? undefined : json['updateTime'],
    };
}

export function WbTaskToJSON(json: any): WbTask {
    return WbTaskToJSONTyped(json, false);
}

export function WbTaskToJSONTyped(value?: WbTask | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'type': value['type'],
        'tag': value['tag'],
        'status': value['status'],
        'progress': value['progress'],
        'priority': value['priority'],
        'parentId': value['parentId'],
        'startTime': value['startTime'],
        'deadline': value['deadline'],
        'completeTime': value['completeTime'],
        'createTime': value['createTime'],
        'updateTime': value['updateTime'],
    };
}

