/* tslint:disable */
/* eslint-disable */
/**
 * Fyrn
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WbTask } from './WbTask';
import {
    WbTaskFromJSON,
    WbTaskFromJSONTyped,
    WbTaskToJSON,
    WbTaskToJSONTyped,
} from './WbTask';

/**
 * 
 * @export
 * @interface WbTaskPageInput
 */
export interface WbTaskPageInput {
    /**
     * 当前页码
     * @type {number}
     * @memberof WbTaskPageInput
     */
    pageNo?: number;
    /**
     * 每页记录数
     * @type {number}
     * @memberof WbTaskPageInput
     */
    pageSize?: number;
    /**
     * 排序字段，默认为id
     * -- GETTER --
     * 获取排序字段，如果为空则返回默认值id
     * @type {string}
     * @memberof WbTaskPageInput
     */
    orderBy?: string;
    /**
     * 排序方向，默认为升序（asc），可选值为asc或desc
     * @type {string}
     * @memberof WbTaskPageInput
     */
    orderDirection?: string;
    /**
     * 
     * @type {WbTask}
     * @memberof WbTaskPageInput
     */
    wbTask?: WbTask;
}

/**
 * Check if a given object implements the WbTaskPageInput interface.
 */
export function instanceOfWbTaskPageInput(value: object): value is WbTaskPageInput {
    return true;
}

export function WbTaskPageInputFromJSON(json: any): WbTaskPageInput {
    return WbTaskPageInputFromJSONTyped(json, false);
}

export function WbTaskPageInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): WbTaskPageInput {
    if (json == null) {
        return json;
    }
    return {
        
        'pageNo': json['pageNo'] == null ? undefined : json['pageNo'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'orderBy': json['orderBy'] == null ? undefined : json['orderBy'],
        'orderDirection': json['orderDirection'] == null ? undefined : json['orderDirection'],
        'wbTask': json['wbTask'] == null ? undefined : WbTaskFromJSON(json['wbTask']),
    };
}

export function WbTaskPageInputToJSON(json: any): WbTaskPageInput {
    return WbTaskPageInputToJSONTyped(json, false);
}

export function WbTaskPageInputToJSONTyped(value?: WbTaskPageInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pageNo': value['pageNo'],
        'pageSize': value['pageSize'],
        'orderBy': value['orderBy'],
        'orderDirection': value['orderDirection'],
        'wbTask': WbTaskToJSON(value['wbTask']),
    };
}

