<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>net.arctel</groupId>
        <artifactId>fyrn-mms</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>fyrn-mms-api</artifactId>
    <name>Fyrn MMS - API Layer</name>
    <description>MMS API 层, 包含 DTO、接口定义等</description>

    <dependencies>
        <!-- OMS 公共依赖 -->
        <dependency>
            <groupId>net.arctel.platform</groupId>
            <artifactId>oms-common</artifactId>
        </dependency>
        <dependency>
            <groupId>net.arctel.platform</groupId>
            <artifactId>oms-api</artifactId>
        </dependency>
        <dependency>
            <groupId>net.arctel</groupId>
            <artifactId>fyrn-mms-domain</artifactId>
        </dependency>
    </dependencies>

</project>