<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>net.arctel.platform</groupId>
        <artifactId>opkit</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>opkit-service</artifactId>
    <dependencies>
        <dependency>
            <groupId>net.arctel.platform</groupId>
            <artifactId>opkit-api</artifactId>
        </dependency>
        <dependency>
            <groupId>net.arctel.platform</groupId>
            <artifactId>opkit-common</artifactId>
        </dependency>

        <dependency>
            <groupId>com.arctel.platform</groupId>
            <artifactId>oms-common</artifactId>
        </dependency>
        <dependency>
            <groupId>com.arctel.platform</groupId>
            <artifactId>oms-infra</artifactId>
        </dependency>


    </dependencies>


</project>